import fs from 'node:fs'
//  typescript转js配置（采用swc包转）
const config = JSON.parse(fs.readFileSync(`${process.cwd()}/.swcrc`, 'utf-8'))

// 缺 WASM 产物时,jest 默认只报「Could not locate module … mapped as …」——
// 说了哪坏了,不说怎么修(AD-142 走查发现的缺口)。在配置加载期定向报错。
if (!fs.existsSync(`${process.cwd()}/excel/excel-wasm/lite/einfach_wasm.js`)) {
  throw new Error(
    'excel/excel-wasm/lite 缺失(WASM 产物未构建)。先跑:\n' +
      '  npm run build:wasm -w @einfach/excel-wasm   # 或根目录 npm run ensureWasm\n' +
      '需要 Rust 工具链 + wasm-pack,见 excel/excel-wasm/README.md。',
  )
}

// 引入一份ts类型，对标typescript开发体验
/** @type {import('jest').Config} */
const jestConfig = {
  // 转译配置
  transform: {
    // 为 Solid.js 的 TSX 文件使用特定的 Babel 配置。
    //
    // 匹配的是绝对路径,按目录段匹配(前后都带 `/`),不会命中
    // node_modules/solid-js。本仓只有 excel/solid-excel 一个 Solid 包 ——
    // @einfach/solid 从 npm 装,发布产物里的 JSX 已由 jsx-dom-expressions
    // 编译过,不需要再过 babel。
    '/solid-excel/.*\\.tsx?$': ['babel-jest'],
    // 其他文件保持现有的 SWC 配置(上面的规则先匹配先生效)。Includes
    // `.mjs` / `.cjs` so ESM-only dependencies (e.g. @lingui/core 6.x and
    // its message-utils helper) get re-emitted as CJS once they're
    // whitelisted from transformIgnorePatterns below.
    '.*\\.(tsx?|jsx?|mjs|cjs)$': ['@swc/jest', { ...config }],
  },
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  /**
   * 运行每个测试文件之前-执行这个路径里面的内容。
   * 这里用来配置@testing-library/jest-dom，
   * 并加载其api-typescript类型补充
   */
  setupFilesAfterEnv: ['<rootDir>/rules/setup-jest.ts'],
  /**
   * 单测里面，如需要使用到dom，这里需设置为jsdom
   */
  testEnvironment: 'jsdom',

  /**
   * Skip generated `@types` directories — composite projects emit `.d.ts`
   * + transpiled `.jsx` there, and jest would re-run those duplicates.
   * Also skip Playwright e2e specs (`excel/solid-excel/e2e/`) — those run under
   * `npm run e2e` from `excel/solid-excel/`, not jest.
   */
  testPathIgnorePatterns: ['/node_modules/', '/@types/', '/excel/solid-excel/e2e/', '/excel/react-excel/e2e/', '/excel/vue-excel/e2e/', '/excel/excel-site/e2e/'],

  /**
   * - excel-wasm/lite/ + excel-wasm/full/: each ships its own package.json
   *   from wasm-pack, both naming the crate `einfach-wasm`, so haste-map
   *   would flag duplicates — and the two dirs collide with each other, not
   *   just with the repo. Regenerated by `npm run build:wasm -w
   *   @einfach/excel-wasm` (lite) and `npm run build:wasm:full` (full).
   * - .claude/: contains agent worktrees during multi-agent development;
   *   each holds a full repo copy that haste-map would dupe-detect.
   */
  modulePathIgnorePatterns: [
    '<rootDir>/excel/excel-wasm/lite/',
    '<rootDir>/excel/excel-wasm/full/',
    '<rootDir>/.claude/',
  ],

  /**
   * 模块名称映射，用于解析 @einfach/core 和 @einfach/react 包
   */
  moduleNameMapper: {
    // 只映射本仓自己的包。@einfach/core 与 @einfach/solid 现在从 npm 安装,
    // 走 node_modules 解析 —— 这正是要验证的:excel 必须能跑在已发布的 core
    // 上,而不是某个只存在于工作区的版本。
    '^@einfach/spreadsheet-ui-core$': '<rootDir>/excel/spreadsheet-ui-core/src',
    '^@einfach/excel-core-ts$': '<rootDir>/excel/excel-core-ts/src',
    // @einfach/excel-wasm 也是本仓的包,但映射到构建产物而非源码 —— 它的"源码"
    // 是 Rust,jest 消费的只能是 wasm-pack 出的 glue。测试侧一律 jest.mock 这两个
    // 入口;真实例化 WASM 的 parity/bench 驱动走 fs 路径直读,不经过 resolver。
    '^@einfach/excel-wasm$': '<rootDir>/excel/excel-wasm/lite/einfach_wasm.js',
    '^@einfach/excel-wasm/full$': '<rootDir>/excel/excel-wasm/full/einfach_wasm.js',
    // CSS / asset imports become an inert object during jest runs so test
    // files that touch a component which `import './foo.css'` still load
    // without a parse error. Solid dialogs co-locate their styles next to
    // the .tsx; without this stub jest would try to parse the .css as JS.
    '\\.(css|less|sass|scss)$': '<rootDir>/rules/css-stub.cjs',
  },

  /**
   * `@lingui/core` (6.x) ships ESM-only (`"type": "module"`,
   * `exports: { ".": "./dist/index.mjs" }`) and pulls in
   * `@lingui/message-utils` + `@messageformat/*` the same way. Jest's
   * default behavior is to skip transforming `node_modules`, which
   * leaves the `import` syntax in place and trips the runtime CommonJS
   * parser. Whitelist the entire chain so SWC transforms them.
   *
   * pnpm hoists into `node_modules/.pnpm/<pkg>@<ver>/node_modules/<pkg>`,
   * so the negative lookahead must match the pnpm-flat path too.
   */
  transformIgnorePatterns: [
    '/node_modules/(?!(\\.pnpm/)?(@lingui|@messageformat)[+/])',
  ],
}
export default jestConfig
