import { expect, test, type Page } from '@playwright/test'

const statistics = (page: Page) => page.getByRole('status', { name: 'Selection statistics' })
const settings = (page: Page) => page.getByRole('button', { name: 'Selection statistics settings' })
const cell = (page: Page, coord: string) => page.locator(`td[data-cell="${coord}"]`)
async function select(page: Page, address: string) {
  const name = page.getByRole('textbox', { name: 'Name box' })
  await name.fill(address)
  await name.press('Enter')
  await expect(page.locator('[data-workbook-grid]')).toHaveAttribute('data-projection-retained', 'false')
}
test.beforeEach(async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/')
  await expect(cell(page, '1:0')).toHaveText('SO-10001')
  await page.getByRole('tab', { name: 'Summary', exact: true }).click()
  await select(page, 'A93:F93')
  await expect(statistics(page)).toContainText('Sum: 26')
})

test('show/hide and restore defaults preserve the native selection, data and history', async ({ page }) => {
  await settings(page).click()
  const dialog = page.getByRole('dialog', { name: 'Selection statistics' })
  for (const checkbox of await dialog.getByRole('checkbox').all()) await checkbox.uncheck()
  await dialog.getByRole('button', { name: 'Done' }).click()
  await expect(statistics(page)).toHaveText('No statistics selected')
  await expect(settings(page)).toBeFocused()
  await expect(page.getByRole('textbox', { name: 'Name box' })).toHaveValue('A93:F93')
  await expect(cell(page, '92:0')).toHaveText('10')
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
  await page.getByRole('tab', { name: 'Sales Orders', exact: true }).click()
  await expect(statistics(page)).toHaveText('No statistics selected')
  await settings(page).click()
  await dialog.getByRole('checkbox', { name: 'Sum', exact: true }).check()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(statistics(page).getByRole('button')).toHaveCount(1)
  await settings(page).click()
  await dialog.getByRole('button', { name: 'Restore defaults' }).click()
  for (const checkbox of await dialog.getByRole('checkbox').all()) await expect(checkbox).toBeChecked()
  await dialog.getByRole('button', { name: 'Done' }).click()
  await expect(statistics(page).getByRole('button')).toHaveCount(6)
  await settings(page).click()
  await dialog.getByRole('checkbox', { name: 'Sum', exact: true }).uncheck()
  await page.reload()
  await expect(statistics(page).getByRole('button', { name: 'Copy Sum' })).toBeVisible()
})

test('copies full precision to the real system clipboard and pastes as a scalar', async ({ page }) => {
  await select(page, 'A95')
  const input = page.getByRole('textbox', { name: 'Active cell value' })
  await input.fill('=1/3')
  await input.press('Enter')
  await select(page, 'A95')
  await expect(statistics(page)).toContainText('Sum: 0.333333333333')
  await statistics(page).getByRole('button', { name: 'Copy Sum' }).click()
  await expect(page.getByLabel('Statistic copy status')).toHaveText('Copied Sum.')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('0.3333333333333333')
  await select(page, 'B95')
  await page.getByRole('button', { name: 'Paste', exact: true }).click()
  await expect(cell(page, '94:1')).toContainText('0.333333')
  await select(page, 'B95')
  await expect(input).toHaveValue('0.3333333333333333')
  await select(page, 'A96')
  await expect(statistics(page).getByRole('button', { name: 'Copy Sum' })).toBeDisabled()
  await statistics(page).getByRole('button', { name: 'Copy Count', exact: true }).click()
  await expect(page.getByLabel('Statistic copy status')).toHaveText('Copied Count.')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('0')
})

test('copying a statistic never creates a cut token or clears the source on paste', async ({ page }) => {
  await select(page, 'A93')
  await page.getByRole('button', { name: 'Cut', exact: true }).click()
  await expect(page.getByLabel('Clipboard status')).toContainText('ready to move')
  await statistics(page).getByRole('button', { name: 'Copy Sum' }).click()
  await expect(page.getByLabel('Statistic copy status')).toHaveText('Copied Sum.')
  const items = await page.evaluate(async () => (await navigator.clipboard.read()).map((item) => item.types))
  expect(items).toEqual([['text/plain']])
  await select(page, 'A95')
  await page.getByRole('button', { name: 'Paste', exact: true }).click()
  await expect(cell(page, '94:0')).toHaveText('10')
  await expect(cell(page, '92:0')).toHaveText('10')
})

test('clipboard denial is visible and retry copies the current selected result', async ({ page }) => {
  await page.evaluate(() => {
    const original = navigator.clipboard.write.bind(navigator.clipboard)
    navigator.clipboard.write = async () => {
      navigator.clipboard.write = original
      throw new DOMException('Denied', 'NotAllowedError')
    }
  })
  await statistics(page).getByRole('button', { name: 'Copy Sum' }).click()
  await expect(page.getByRole('alert', { name: 'Statistic copy status' })).toContainText('permission was denied')
  await select(page, 'C93')
  await expect(statistics(page)).toContainText('Min: -4')
  await statistics(page).getByRole('button', { name: 'Copy Min' }).click()
  await expect(page.getByLabel('Statistic copy status')).toHaveText('Copied Min.')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('-4')
})

for (const width of [1280, 390]) {
  test(`settings and copy feedback remain usable at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 800 })
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await settings(page).click()
    const dialog = page.getByRole('dialog', { name: 'Selection statistics' })
    await expect(dialog.getByRole('checkbox', { name: 'Count', exact: true })).toBeFocused()
    await page.keyboard.press('Space')
    await expect(dialog.getByRole('checkbox', { name: 'Count', exact: true })).not.toBeChecked()
    for (const control of await dialog.locator('input, button').all()) await expect(control).toBeInViewport()
    await page.screenshot({ path: info.outputPath(`statistics-settings-${width}.png`) })
    await page.keyboard.press('Escape')
    await expect(settings(page)).toBeFocused()
    await statistics(page).getByRole('button', { name: 'Copy Sum' }).click()
    await expect(page.getByLabel('Statistic copy status')).toHaveText('Copied Sum.')
    await expect(page.getByLabel('Statistic copy status')).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('tab', { name: 'Sales Orders', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Sales Orders', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(cell(page, '1:0')).toHaveText('SO-10001')
    await expect(statistics(page).getByRole('button', { name: 'Copy Sum' })).toBeVisible()
    await page.screenshot({ path: info.outputPath(`statistics-copy-${width}.png`) })
    expect(errors).toEqual([])
  })
}
