import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, test } from '@jest/globals'
import { ENGINE_BUILTIN_FORMULA_NAMES } from '../src/custom-formulas'

/**
 * Drift guard: `engine-builtin-names.ts` must stay byte-for-byte
 * equivalent (as a set) to the Rust engine's `is_builtin_function_name`
 * arms.
 *
 * Why this matters: the reserved-name list is what stops a host from
 * registering a JS custom formula whose name an engine built-in would
 * shadow. Evaluation precedence is `built-in → defined-name LAMBDA →
 * host custom formula → #NAME?` (see `eval_named_call`'s Precedence
 * note in `excel/rust/excel-core/src/eval.rs`), so a name that is
 * missing from the JS mirror gets accepted at registration time and
 * then silently never runs.
 *
 * The mirror is generated by
 * `excel/spreadsheet-ui-core/scripts/extract-builtin-names.mjs`, but
 * nothing forced anyone to re-run it. This test is that force.
 *
 * Scope note: this asserts `Rust reserved list == JS mirror` — the
 * second half of the chain. The first half, `eval_func dispatch ⊇ Rust
 * reserved list` (diff pinned to an explicit `REGEX*` whitelist), is
 * asserted on the Rust side by
 * `excel/rust/excel-core/tests/reserved_name_parity.rs`. It lives there
 * because whoever adds a built-in runs `cargo test`, not this suite.
 * Do not duplicate that assertion here — one extractor per invariant.
 */

const EVAL_RS_PATH = join(process.cwd(), 'excel/rust/excel-core/src/eval.rs')

/**
 * Self-check floor for the extractor — a floor, not the real count, so
 * adding built-ins never means editing this constant. The point is to
 * fail loudly if the extraction regex stops matching (returning 0 or a
 * handful of names), which would otherwise make the bidirectional set
 * comparison pass vacuously against an equally-empty diff.
 */
const MIN_EXTRACTED_NAMES = 400

/** Names that must be in any sane extraction — a shape check on top of the count. */
const ANCHOR_NAMES = ['SUM', 'IF', 'LAMBDA', 'LET', 'XLOOKUP', 'MAP', 'REDUCE', 'T.DIST']

/**
 * Slice the body of the `matches!(...)` macro inside
 * `pub fn is_builtin_function_name`. Deliberately narrow: pulling
 * string literals from the whole 39k-line file would drag in unrelated
 * identifiers.
 */
function readReservedNameMacroBody(): string {
  const src = readFileSync(EVAL_RS_PATH, 'utf8')
  const fnIdx = src.indexOf('pub fn is_builtin_function_name')
  if (fnIdx === -1) {
    throw new Error(`'pub fn is_builtin_function_name' not found in ${EVAL_RS_PATH}`)
  }
  const macroIdx = src.indexOf('matches!(', fnIdx)
  if (macroIdx === -1) {
    throw new Error('matches!(...) macro not found after is_builtin_function_name')
  }
  let depth = 0
  for (let i = src.indexOf('(', macroIdx); i < src.length; i++) {
    if (src[i] === '(') depth++
    else if (src[i] === ')') {
      depth--
      if (depth === 0) return src.slice(macroIdx, i)
    }
  }
  throw new Error('unbalanced matches!(...) parens in is_builtin_function_name')
}

function extractReservedNames(body: string): string[] {
  return Array.from(body.matchAll(/"([A-Z][A-Z0-9_.]*)"/g)).map((m) => m[1])
}

describe('engine-builtin mirror: Rust is_builtin_function_name vs JS ENGINE_BUILTIN_FORMULA_NAMES', () => {
  const macroBody = readReservedNameMacroBody()
  const rustNames = extractReservedNames(macroBody)

  // --- extractor self-checks (guard against a false green) ---

  test('extraction pulled a plausible number of names', () => {
    expect(rustNames.length).toBeGreaterThanOrEqual(MIN_EXTRACTED_NAMES)
  })

  test('extraction contains the canonical anchor names', () => {
    for (const name of ANCHOR_NAMES) {
      expect(rustNames).toContain(name)
    }
  })

  test('the Rust reserved list is not #[cfg]-gated', () => {
    // If arms ever get feature-gated (as the REGEX* dispatch arms in
    // `eval_func` are), a plain string extraction would silently mirror
    // the union of all build configurations while any single build
    // reserves a subset. Fail here and decide what the mirror means
    // before changing this test.
    expect(macroBody).not.toContain('#[cfg(')
  })

  // --- the actual mirror assertion ---

  test('Rust reserved list and JS mirror are the same set', () => {
    const rust = new Set(rustNames)
    const js = new Set(ENGINE_BUILTIN_FORMULA_NAMES)

    const missingInJs = [...rust].filter((n) => !js.has(n)).sort()
    const extraInJs = [...js].filter((n) => !rust.has(n)).sort()

    // Compared as one object so a failure prints both directions of the
    // drift, each name listed individually. Fix by re-running
    // `node excel/spreadsheet-ui-core/scripts/extract-builtin-names.mjs`.
    expect({ missingInJs, extraInJs }).toEqual({ missingInJs: [], extraInJs: [] })
  })

  test('JS mirror has no duplicates and stays sorted', () => {
    // The generator emits a sorted, de-duplicated array. A hand edit is
    // the only way to break either property, and duplicates would hide
    // from the set comparison above.
    const names = [...ENGINE_BUILTIN_FORMULA_NAMES]
    expect(new Set(names).size).toBe(names.length)
    expect(names).toEqual([...names].sort())
  })

  test('the generated header count matches the array length', () => {
    const generated = readFileSync(
      join(process.cwd(), 'excel/spreadsheet-ui-core/src/custom-formulas/engine-builtin-names.ts'),
      'utf8',
    )
    const declared = /Count: (\d+) names\./.exec(generated)
    expect(declared).not.toBeNull()
    expect(Number(declared![1])).toBe(ENGINE_BUILTIN_FORMULA_NAMES.length)
  })
})
