import { expect, test, type Page } from '@playwright/test'

const cell = (page: Page, coord: string) => page.locator(`td[data-cell="${coord}"]`)
const dialog = (page: Page) => page.getByRole('dialog', { name: 'Fill series', exact: true })
async function select(page: Page, address: string) {
  const name = page.getByRole('textbox', { name: 'Name box' })
  await name.fill(address)
  await name.press('Enter')
  await expect(name).toHaveValue(address)
  await expect(page.locator('[data-workbook-grid]')).toHaveAttribute('data-projection-retained', 'false')
}
async function write(page: Page, address: string, value: string) {
  await select(page, address)
  const input = page.getByRole('textbox', { name: 'Active cell value' })
  await input.fill(value)
  await input.press('Enter')
}
async function open(page: Page, address: string, count = '1') {
  await select(page, address)
  await page.getByRole('button', { name: 'Fill series', exact: true }).click()
  await dialog(page).getByLabel('Sequence type').selectOption('date')
  await dialog(page).getByLabel('Source sample count').fill(count)
}
async function apply(page: Page) {
  await dialog(page).getByRole('button', { name: 'Apply series', exact: true }).click()
  await expect(dialog(page)).toHaveCount(0)
}
async function drag(page: Page, address: string, target: string, copy = false) {
  await select(page, address)
  await page.getByRole('button', { name: 'Drag to fill' }).hover()
  await page.mouse.down()
  const box = await cell(page, target).boundingBox()
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2, { steps: 5 })
  if (copy) await page.keyboard.down('Control')
  await page.mouse.up()
  if (copy) await page.keyboard.up('Control')
  await expect(page.getByLabel('Fill status')).toContainText('Filled')
}
test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await expect(cell(page, '1:0')).toHaveText('SO-10001')
  await page.getByRole('tab', { name: 'Summary', exact: true }).click()
})

test('seed dates retain bold, italic, underline and the compatibility leap day', async ({ page }) => {
  await select(page, 'A20')
  await expect(cell(page, '19:0')).toHaveText('2024-02-28')
  await expect(cell(page, '19:0')).toHaveCSS('font-weight', '700')
  await expect(cell(page, '19:2')).toHaveText('2024-01-31')
  await expect(cell(page, '20:2')).toHaveText('2024-02-29')
  await expect(cell(page, '19:2')).toHaveCSS('font-style', 'italic')
  await expect(cell(page, '19:4')).toHaveText('1900-02-29')
  await expect(cell(page, '19:4')).toHaveCSS('text-decoration-line', 'underline')
})

test('cell and formula-bar input share numeric dates; undo restores both value and format', async ({ page }) => {
  await select(page, 'A80')
  await cell(page, '79:0').dblclick()
  const editor = page.getByRole('textbox', { name: 'Cell editor' })
  await editor.fill('2024/2/29')
  await editor.press('Enter')
  await expect(cell(page, '79:0')).toHaveText('2024-02-29')
  await select(page, 'A80')
  await expect(page.getByRole('textbox', { name: 'Active cell value' })).toHaveValue('45351')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '79:0')).toHaveText('')
  await expect(page.getByRole('button', { name: 'General format' })).toHaveAttribute('aria-pressed', 'true')
  await write(page, 'A80', '2024-02-29')
  await write(page, 'B80', '=DAY(A80)')
  await expect(cell(page, '79:1')).toHaveText('29')
  await write(page, 'C80', '2023-02-29')
  await expect(cell(page, '79:2')).toHaveText('2023-02-29')
  await write(page, 'D80', "'2024-02-29")
  await select(page, 'D80')
  await expect(page.getByRole('textbox', { name: 'Active cell value' })).toHaveValue("'2024-02-29")
  await expect(page.getByRole('button', { name: 'General format' })).toHaveAttribute('aria-pressed', 'true')
})

test('date format changes display only and array formula anchors use the same native display', async ({ page }) => {
  await write(page, 'A80', '60')
  await select(page, 'A80')
  await page.getByRole('button', { name: 'Date format' }).click()
  await expect(cell(page, '79:0')).toHaveText('1900-02-29')
  await expect(page.getByRole('textbox', { name: 'Active cell value' })).toHaveValue('60')
  await page.getByRole('button', { name: 'General format' }).click()
  await expect(cell(page, '79:0')).toHaveText('60')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '79:0')).toHaveText('1900-02-29')
  await write(page, 'A80', '=SEQUENCE(1,1,60)')
  await expect(cell(page, '79:0')).toHaveText('1900-02-29')
  await select(page, 'A80')
  await expect(page.getByRole('textbox', { name: 'Active cell value' })).toHaveValue('=SEQUENCE(1,1,60)')
})

test('date series infers day, week and month ends from native samples', async ({ page }) => {
  await open(page, 'A20:A23')
  await apply(page)
  await expect(cell(page, '20:0')).toHaveText('2024-02-29')
  await expect(cell(page, '22:0')).toHaveText('2024-03-02')
  await expect(cell(page, '22:0')).toHaveCSS('font-weight', '700')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '22:0')).toHaveText('')
  await open(page, 'C20:C24', '2')
  await apply(page)
  await expect(cell(page, '21:2')).toHaveText('2024-03-31')
  await expect(cell(page, '22:2')).toHaveText('2024-04-30')
  await expect(cell(page, '23:2')).toHaveText('2024-05-31')
  await write(page, 'A30', '2024-01-01')
  await write(page, 'A31', '2024-01-08')
  await open(page, 'A30:A33', '2')
  await apply(page)
  await expect(cell(page, '32:0')).toHaveText('2024-01-22')
})

test('date fill handles detect month ends, fill backwards and honor the copy modifier', async ({ page }) => {
  await drag(page, 'C20:C21', '23:2')
  await expect(cell(page, '23:2')).toHaveText('2024-05-31')
  await drag(page, 'E20', '21:4', true)
  await expect(cell(page, '21:4')).toHaveText('1900-02-29')
  await drag(page, 'E20', '18:4')
  await expect(cell(page, '18:4')).toHaveText('1900-02-28')
  await write(page, 'F30', '2024-03-31')
  await write(page, 'E30', '2024-02-29')
  await drag(page, 'E30:F30', '29:3')
  await expect(cell(page, '29:3')).toHaveText('2024-01-31')
})

test('irregular date samples reject explicit series but automatically copy without data loss', async ({ page }) => {
  await write(page, 'A30', '2024-01-01')
  await write(page, 'A31', '2024-01-02')
  await write(page, 'A32', '2024-01-04')
  await open(page, 'A30:A34', '3')
  await dialog(page).getByRole('button', { name: 'Apply series' }).click()
  await expect(dialog(page).getByRole('alert')).toContainText('sequence')
  await expect(cell(page, '32:0')).toHaveText('')
  await page.keyboard.press('Escape')
  await drag(page, 'A30:A32', '33:0')
  await expect(cell(page, '32:0')).toHaveText('2024-01-01')
  await expect(cell(page, '33:0')).toHaveText('2024-01-02')
})

test('auto-fit measures the native date display instead of a serial or JS leap-day conversion', async ({ page }) => {
  await page.getByRole('button', { name: 'New sheet', exact: true }).click()
  await expect(page.locator('[data-workbook-grid]')).toHaveAttribute('aria-label', 'Sheet3 cells')
  await write(page, 'A1', '=SEQUENCE(1,1,60)')
  await select(page, 'A1')
  await page.getByRole('button', { name: 'Date format' }).click()
  await expect(cell(page, '0:0')).toHaveText('1900-02-29')
  const handle = page.getByRole('separator', { name: 'Resize column A', exact: true })
  await handle.dblclick()
  await expect.poll(async () => Number(await handle.getAttribute('aria-valuenow'))).toBeLessThan(120)
  expect(Number(await handle.getAttribute('aria-valuenow'))).toBeGreaterThan(70)
  const text = cell(page, '0:0').locator('.cell-content')
  expect(await text.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true)
  await expect(page.getByRole('textbox', { name: 'Active cell value' })).toHaveValue('=SEQUENCE(1,1,60)')
})

test('a thousand-row date series reaches offscreen data and undoes in one step', async ({ page }) => {
  await page.getByRole('tab', { name: 'Sales Orders', exact: true }).click()
  await write(page, 'A2', '2024-01-01')
  await open(page, 'A2:A1001')
  await apply(page)
  await select(page, 'A1001')
  await expect(cell(page, '1000:0')).toHaveText('2026-09-26')
  await expect(page.getByRole('textbox', { name: 'Active cell value' })).toHaveValue('46291')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '1000:0')).toHaveText('SO-11000')
})

test('external TSV preserves destination formatting; internal copy and Copy As retain dates', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.evaluate(() => navigator.clipboard.writeText('2024-02-29'))
  await select(page, 'A80')
  await page.getByRole('button', { name: 'Paste', exact: true }).click()
  await expect(cell(page, '79:0')).toHaveText('45351')
  await select(page, 'E20')
  await page.getByRole('button', { name: 'Copy', exact: true }).click()
  await expect(page.getByLabel('Clipboard status')).toContainText('Copied')
  await select(page, 'B80')
  await page.getByRole('button', { name: 'Paste', exact: true }).click()
  await expect(cell(page, '79:1')).toHaveText('1900-02-29')
  await expect(cell(page, '79:1')).toHaveCSS('text-decoration-line', 'underline')
  await page.getByRole('combobox', { name: 'Copy as' }).selectOption('text')
  await expect(page.getByLabel('Clipboard status')).toContainText('as text.')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('1900-02-29')
})

for (const width of [1280, 390]) {
  test(`date panel and rejected overflow remain usable at ${width}px`, async ({ page }, info) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.setViewportSize({ width, height: 800 })
    await write(page, 'A30', '9999-12-31')
    await open(page, 'A30:A32')
    for (const control of await dialog(page).locator('input, select, button').all())
      await expect(control).toBeInViewport()
    await page.screenshot({ path: info.outputPath(`date-${width}.png`) })
    await dialog(page).getByRole('button', { name: 'Apply series' }).click()
    await expect(dialog(page).getByRole('alert')).toBeInViewport()
    await expect(cell(page, '30:0')).toHaveText('')
    await page.screenshot({ path: info.outputPath(`date-error-${width}.png`) })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: 'Fill series', exact: true })).toBeFocused()
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(cell(page, '29:0')).toHaveText('')
  })
}
