import { expect, test, type Page } from '@playwright/test'

const cell = (page: Page, coord: string) => page.locator(`td[data-cell="${coord}"]`)
const dialog = (page: Page) => page.getByRole('dialog', { name: 'Fill series', exact: true })
const input = (page: Page) => page.getByRole('textbox', { name: 'Active cell value' })
async function select(page: Page, address: string) {
  const name = page.getByRole('textbox', { name: 'Name box' })
  await name.fill(address)
  await name.press('Enter')
  await expect(name).toHaveValue(address)
  await expect(page.locator('[data-workbook-grid]')).toHaveAttribute('data-projection-retained', 'false')
}
async function open(page: Page, address: string, kind = 'number', count = '2') {
  await select(page, address)
  await page.getByRole('button', { name: 'Fill series', exact: true }).click()
  await dialog(page).getByLabel('Sequence type').selectOption(kind)
  await dialog(page).getByLabel('Source sample count').fill(count)
}
async function apply(page: Page) {
  await dialog(page).getByRole('button', { name: 'Apply series', exact: true }).click()
  await expect(dialog(page)).toHaveCount(0)
}
async function write(page: Page, address: string, value: string) {
  await select(page, address)
  await input(page).fill(value)
  await input(page).press('Enter')
  await select(page, address)
  await expect(input(page)).toHaveValue(value)
}
test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await expect(cell(page, '1:0')).toHaveText('SO-10001')
  await page.getByRole('tab', { name: 'Summary', exact: true }).click()
  await select(page, 'A39')
  await expect(cell(page, '38:0')).toHaveText('Series examples')
})

test('native number seed extends with one undo step while source samples stay intact', async ({ page }) => {
  await open(page, 'A40:A44')
  await apply(page)
  for (const [row, value] of [[39, '1'], [40, '3'], [41, '5'], [42, '7'], [43, '9']] as const)
    await expect(cell(page, `${row}:0`)).toHaveText(value)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '41:0')).toHaveText('')
  await expect(cell(page, '43:0')).toHaveText('')
  await expect(cell(page, '40:0')).toHaveText('3')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(cell(page, '43:0')).toHaveText('9')
  await select(page, 'B44')
  await input(page).fill('=A44*2')
  await input(page).press('Enter')
  await expect(cell(page, '43:1')).toHaveText('18')
})

test('horizontal decimals and decreasing sequences are inferred without JS values', async ({ page }) => {
  await write(page, 'A50', '0.25')
  await write(page, 'B50', '0.75')
  await open(page, 'A50:E50')
  await expect(dialog(page).getByLabel('Direction')).toHaveValue('right')
  await apply(page)
  await expect(cell(page, '49:4')).toHaveText('2.25')
  await write(page, 'A50', '4.5')
  await write(page, 'B50', '3')
  await open(page, 'A50:D50')
  await apply(page)
  await expect(cell(page, '49:2')).toHaveText('1.5')
  await expect(cell(page, '49:3')).toHaveText('0')
})

test('text numbering preserves padding and native seed formatting', async ({ page }) => {
  await open(page, 'C40:C44', 'text-number')
  await apply(page)
  await expect(cell(page, '41:2')).toHaveText('Item005')
  await expect(cell(page, '43:2')).toHaveText('Item009')
  await expect(cell(page, '43:2')).toHaveCSS('font-style', 'italic')
  await select(page, 'C44')
  await expect(input(page)).toHaveValue('Item009')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '43:2')).toHaveText('')
  await select(page, 'C40')
  await expect(cell(page, '39:2')).toHaveText('Item001')
})

test('nonuniform samples reject arithmetic but a four-sample linear trend can retry', async ({ page }) => {
  await open(page, 'E40:E45', 'number', '4')
  await dialog(page).getByRole('button', { name: 'Apply series' }).click()
  await expect(dialog(page).getByRole('alert')).toContainText('source values do not match')
  await expect(cell(page, '43:4')).toHaveText('')
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
  await dialog(page).getByLabel('Sequence type').selectOption('linear-trend')
  await dialog(page).getByLabel('Source sample count').fill('4')
  await apply(page)
  await expect(cell(page, '43:4')).toHaveText('5.5')
  await expect(cell(page, '44:4')).toHaveText('6.9')
  await expect(cell(page, '42:4')).toHaveText('5')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '43:4')).toHaveText('')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(cell(page, '44:4')).toHaveText('6.9')
})

test('formula samples reject without overwriting a destination and cancel restores focus', async ({ page }) => {
  await open(page, 'B71:B73')
  await dialog(page).getByRole('button', { name: 'Apply series' }).click()
  await expect(dialog(page).getByRole('alert')).toContainText('non-formula numbers')
  await expect(cell(page, '72:1')).toHaveText('')
  await page.keyboard.press('Escape')
  await expect(dialog(page)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Fill series', exact: true })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
})

test('invalid geometry and count never allocate native history', async ({ page }) => {
  await open(page, 'A40:B44')
  await dialog(page).getByRole('button', { name: 'Apply series' }).click()
  await expect(dialog(page).getByRole('alert')).toContainText('one row or column')
  await dialog(page).getByRole('button', { name: 'Cancel' }).click()
  await open(page, 'A40:A44', 'number', '5')
  await dialog(page).getByRole('button', { name: 'Apply series' }).click()
  await expect(dialog(page).getByRole('alert')).toContainText('at least one destination')
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
})

test('a thousand-row sequence reaches the final native record and one undo restores targets', async ({ page }) => {
  await page.getByRole('tab', { name: 'Sales Orders', exact: true }).click()
  await write(page, 'A2', '1')
  await write(page, 'A3', '3')
  await open(page, 'A2:A1001')
  await apply(page)
  await select(page, 'A1001')
  await expect(cell(page, '1000:0')).toHaveText('1999')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '1000:0')).toHaveText('SO-11000')
  await select(page, 'A2')
  await expect(cell(page, '1:0')).toHaveText('1')
})

test('hidden targets participate and existing clipboard snapshot is unchanged', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await select(page, 'A40')
  await page.getByRole('button', { name: 'Copy', exact: true }).click()
  await expect(page.getByLabel('Clipboard status')).toContainText('Copied')
  await write(page, 'H8', '1')
  await write(page, 'H9', '3')
  await open(page, 'H8:H12')
  await apply(page)
  await page.getByRole('combobox', { name: 'Row and column visibility' }).selectOption('unhide-all')
  await select(page, 'H10')
  await expect(cell(page, '9:7')).toHaveText('5')
  await select(page, 'H14')
  await page.getByRole('button', { name: 'Paste', exact: true }).click()
  await expect(cell(page, '13:7')).toHaveText('1')
})

for (const width of [1280, 390]) {
  test(`sequence panel focus, error and controls remain usable at ${width}px`, async ({ page }, info) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.setViewportSize({ width, height: 800 })
    await open(page, 'E40:E45', 'linear-trend', '4')
    for (const control of await dialog(page).locator('input, select, button').all())
      await expect(control).toBeInViewport()
    await page.screenshot({ path: info.outputPath(`series-${width}.png`) })
    await dialog(page).getByLabel('Source sample count').fill('10')
    await dialog(page).getByRole('button', { name: 'Apply series' }).click()
    await expect(dialog(page).getByRole('alert')).toBeInViewport()
    await page.screenshot({ path: info.outputPath(`series-error-${width}.png`) })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: 'Fill series', exact: true })).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
  })
}
