import { expect, test, type Page } from '@playwright/test'

const cell = (page: Page, coord: string) => page.locator(`td[data-cell="${coord}"]`)
const menu = (page: Page) => page.getByRole('combobox', { name: 'Sort selected range' })
const input = (page: Page) => page.getByRole('textbox', { name: 'Active cell value' })
async function select(page: Page, address: string) {
  const name = page.getByRole('textbox', { name: 'Name box' })
  await name.fill(address)
  await name.press('Enter')
  await expect(name).toHaveValue(address)
  await expect(page.locator('[data-workbook-grid]')).toHaveAttribute('data-projection-retained', 'false')
}
async function write(page: Page, address: string, value: string) {
  await select(page, address)
  await input(page).fill(value)
  await input(page).press('Enter')
  await select(page, address)
  await expect(input(page)).toHaveValue(value)
}
async function sort(page: Page, direction: 'asc' | 'desc') {
  await menu(page).selectOption(direction)
  await expect(page.getByLabel('Sort status')).toHaveText(/Sorted \d+ rows\.|Already in order\./)
}
async function records(page: Page, expected: string[]) {
  for (let index = 0; index < expected.length; index++)
    await expect(cell(page, `${25 + index}:2`)).toHaveText(expected[index]!)
}
test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await expect(cell(page, '1:0')).toHaveText('SO-10001')
  await page.getByRole('tab', { name: 'Summary', exact: true }).click()
  await select(page, 'A25:C29')
  await expect(cell(page, '24:0')).toHaveText('Team')
  await records(page, ['W20', 'E10', 'W10', 'E30'])
})

test('ascending sort moves complete records and styles, with one undo/redo step', async ({ page }) => {
  await select(page, 'A26:C29')
  await sort(page, 'asc')
  await records(page, ['E10', 'E30', 'W20', 'W10'])
  await expect(cell(page, '25:2')).toHaveCSS('font-style', 'italic')
  await expect(cell(page, '26:2')).toHaveCSS('text-decoration-line', 'underline')
  await expect(cell(page, '27:2')).toHaveCSS('font-weight', '700')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await records(page, ['W20', 'E10', 'W10', 'E30'])
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await records(page, ['E10', 'E30', 'W20', 'W10'])
})

test('descending numeric sort is stable and a repeated sort creates no history step', async ({ page }) => {
  await select(page, 'B26:C29')
  await sort(page, 'desc')
  await records(page, ['E30', 'W20', 'E10', 'W10'])
  await sort(page, 'desc')
  await expect(page.getByLabel('Sort status')).toHaveText('Already in order.')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await records(page, ['W20', 'E10', 'W10', 'E30'])
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
})

test('custom sort keeps the header and uses ordered, mixed-direction keys', async ({ page }) => {
  await menu(page).selectOption('custom')
  const dialog = page.getByRole('dialog', { name: 'Custom sort' })
  await dialog.getByLabel('First row is a header').check()
  await dialog.getByRole('button', { name: 'Add level' }).click()
  await dialog.getByLabel('Sort order 2').selectOption('desc')
  await dialog.getByRole('button', { name: 'Apply sort' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(menu(page)).toBeFocused()
  await expect(cell(page, '24:0')).toHaveText('Team')
  await expect(cell(page, '24:1')).toHaveText('Score')
  await records(page, ['E30', 'E10', 'W20', 'W10'])
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await records(page, ['W20', 'E10', 'W10', 'E30'])
})

test('blank cells stay last in both directions and formulas remain formulas', async ({ page }) => {
  await write(page, 'B26', '=5+5')
  await select(page, 'B26:C30')
  await sort(page, 'desc')
  await records(page, ['E30', 'W20', 'E10', 'W10'])
  await expect(cell(page, '29:1')).toHaveText('')
  await select(page, 'B27')
  await expect(input(page)).toHaveValue('=5+5')
  await select(page, 'B26:C30')
  await sort(page, 'asc')
  await records(page, ['W20', 'E10', 'W10', 'E30'])
  await expect(cell(page, '29:1')).toHaveText('')
})

test('hidden rows are included without moving the hidden-row setting', async ({ page }) => {
  await select(page, 'A27')
  await page.getByRole('combobox', { name: 'Row and column visibility' }).selectOption('hide-rows')
  await select(page, 'A26:C29')
  await sort(page, 'asc')
  await expect(cell(page, '25:2')).toHaveText('E10')
  await expect(cell(page, '26:2')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Row and column visibility' }).selectOption('unhide-all')
  await records(page, ['E10', 'E30', 'W20', 'W10'])
})

test('merged ranges and live array spills reject without a sort history entry', async ({ page }) => {
  await select(page, 'A15:D18')
  await menu(page).selectOption('asc')
  await expect(page.getByRole('alert', { name: 'Sort status' })).toContainText('Unmerge')
  await expect(cell(page, '14:0')).toHaveText('Merged heading')
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
  await write(page, 'E25', '=SEQUENCE(3)')
  await select(page, 'E25:E28')
  await menu(page).selectOption('asc')
  await expect(page.getByRole('alert', { name: 'Sort status' })).toContainText('array spill')
  await expect(cell(page, '25:4')).toHaveText('2')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '24:4')).toHaveText('')
})

test('single-cell rejection and dialog cancellation leave data untouched', async ({ page }) => {
  await select(page, 'A26')
  await menu(page).selectOption('asc')
  await expect(page.getByRole('alert', { name: 'Sort status' })).toContainText('at least two')
  await select(page, 'A25:C29')
  await menu(page).selectOption('custom')
  await page.getByRole('button', { name: 'Add level' }).click()
  await page.getByLabel('Remove sort level 2').click()
  await expect(page.getByLabel('Sort column 2')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(menu(page)).toBeFocused()
  await records(page, ['W20', 'E10', 'W10', 'E30'])
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
})

test('1,000 records sort through Rust; cross-sheet dependents update and undo restores', async ({ page }) => {
  await page.getByRole('tab', { name: 'Sales Orders', exact: true }).click()
  await select(page, 'A2:P1001')
  await sort(page, 'desc')
  await select(page, 'A2')
  await expect(cell(page, '1:0')).toHaveText('SO-11000')
  const lastCustomer = await cell(page, '1:1').textContent()
  await page.getByRole('tab', { name: 'Summary', exact: true }).click()
  await select(page, 'B2')
  await expect(cell(page, '1:1')).toHaveText(lastCustomer!)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('tab', { name: 'Sales Orders', exact: true }).click()
  await select(page, 'A2')
  await expect(cell(page, '1:0')).toHaveText('SO-10001')
  await select(page, 'A1001')
  await expect(cell(page, '1000:0')).toHaveText('SO-11000')
})

test('sorting preserves copy snapshots but rejects a stale cut source', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await select(page, 'C26')
  await page.getByRole('button', { name: 'Copy', exact: true }).click()
  await expect(page.getByLabel('Clipboard status')).toContainText('Copied')
  await select(page, 'A26:C29')
  await sort(page, 'asc')
  await select(page, 'E30')
  await page.getByRole('button', { name: 'Paste', exact: true }).click()
  await expect(cell(page, '29:4')).toHaveText('W20')
  await select(page, 'A26')
  await page.getByRole('button', { name: 'Cut', exact: true }).click()
  await expect(page.getByLabel('Clipboard status')).toContainText('ready to move')
  await select(page, 'A26:C29')
  await sort(page, 'desc')
  await select(page, 'E31')
  await page.getByRole('button', { name: 'Paste', exact: true }).click()
  await expect(page.getByRole('alert', { name: 'Clipboard status' })).toContainText('Copy or cut again')
  await expect(cell(page, '30:4')).toHaveText('')
  await select(page, 'A26')
  await expect(cell(page, '25:0')).toHaveText('West')
})

for (const width of [1280, 390]) {
  test(`sort panel remains usable at ${width}px`, async ({ page }, info) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.setViewportSize({ width, height: 800 })
    await menu(page).selectOption('custom')
    const dialog = page.getByRole('dialog', { name: 'Custom sort' })
    await dialog.getByLabel('First row is a header').check()
    await dialog.getByRole('button', { name: 'Add level' }).click()
    await dialog.getByLabel('Sort order 2').selectOption('desc')
    for (const name of ['Sort column 1', 'Sort order 1', 'Sort column 2', 'Sort order 2'])
      await expect(dialog.getByLabel(name)).toBeInViewport()
    await expect(dialog.getByRole('button', { name: 'Apply sort' })).toBeInViewport()
    expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath(`sort-${width}.png`) })
    await dialog.getByRole('button', { name: 'Apply sort' }).click()
    await expect(dialog).not.toBeVisible()
    await select(page, 'C26')
    await expect(cell(page, '25:2')).toHaveText('E30')
    expect(errors).toEqual([])
  })
}
