export interface ModalSurface {
  readonly id: string
  readonly name: string
  readonly rootClass: string
  readonly headerClass: string
  readonly footerClass: string
  readonly controlClass: string
  readonly expectedWidth: number
  readonly anchored?: boolean
  readonly hasPrimary?: boolean
}

/** D01-D17: production class names used to expose feature overrides in the CSSOM matrix. */
export const MODAL_SURFACES: readonly ModalSurface[] = [
  {
    id: 'D01',
    name: 'Find and Replace',
    rootClass: 'find-replace-dialog',
    headerClass: 'fr-header',
    footerClass: 'fr-footer',
    controlClass: 'fr-btn',
    expectedWidth: 480,
  },
  {
    id: 'D02',
    name: 'Go To',
    rootClass: 'go-to-dialog',
    headerClass: 'gt-header',
    footerClass: 'gt-footer',
    controlClass: 'gt-btn',
    expectedWidth: 420,
  },
  {
    id: 'D03',
    name: 'Paste Special',
    rootClass: 'paste-special-dialog',
    headerClass: 'ps-header',
    footerClass: 'ps-footer',
    controlClass: 'ps-btn',
    expectedWidth: 420,
  },
  {
    id: 'D04',
    name: 'Text to Columns',
    rootClass: 'text-to-columns-dialog',
    headerClass: 'ttc-header',
    footerClass: 'ttc-footer',
    controlClass: 'ttc-btn',
    expectedWidth: 600,
  },
  {
    id: 'D05',
    name: 'Remove Duplicates',
    rootClass: 'remove-duplicates-dialog',
    headerClass: 'rd-header',
    footerClass: 'rd-footer',
    controlClass: 'rd-btn',
    expectedWidth: 480,
  },
  {
    id: 'D06',
    name: 'Conditional Formatting',
    rootClass: 'conditional-format-dialog',
    headerClass: 'cf-dialog-header',
    footerClass: 'cf-dialog-footer',
    controlClass: 'cf-dialog-button',
    expectedWidth: 560,
  },
  {
    id: 'D07',
    name: 'Data Validation',
    rootClass: 'validation-dialog spreadsheet-validation-dialog',
    headerClass: 'dv-dialog-header',
    footerClass: 'dv-dialog-footer',
    controlClass: 'validation-cancel-button',
    expectedWidth: 520,
  },
  {
    id: 'D08',
    name: 'Name Manager',
    rootClass: 'name-manager-dialog',
    headerClass: 'nm-header',
    footerClass: 'nm-actions',
    controlClass: 'nm-btn',
    expectedWidth: 680,
  },
  {
    id: 'D09',
    name: 'Format Cells',
    rootClass: 'format-cells-dialog',
    headerClass: 'format-cells-header',
    footerClass: 'format-cells-actions',
    controlClass: 'format-cells-button',
    expectedWidth: 560,
  },
  {
    id: 'D10',
    name: 'More Number Formats',
    rootClass: 'number-format-dialog',
    headerClass: 'number-format-dialog-header',
    footerClass: 'number-format-dialog-actions',
    controlClass: 'number-format-dialog-button',
    expectedWidth: 440,
  },
  {
    id: 'D11',
    name: 'Page Setup',
    rootClass: 'spreadsheet-page-setup-dialog',
    headerClass: 'page-setup-header',
    footerClass: 'page-setup-footer',
    controlClass: 'page-setup-button',
    expectedWidth: 440,
  },
  {
    id: 'D12',
    name: 'Sort Confirmation',
    rootClass: 'spreadsheet-sort-confirmation-dialog',
    headerClass: 'spreadsheet-sort-confirmation-header',
    footerClass: 'spreadsheet-sort-confirmation-actions',
    controlClass: 'sort-confirmation-button',
    expectedWidth: 360,
  },
  {
    id: 'D13',
    name: 'Protection Unlock',
    rootClass: 'protection-unlock-dialog',
    headerClass: 'protection-unlock-header',
    footerClass: 'protection-unlock-actions',
    controlClass: 'protection-unlock-btn',
    expectedWidth: 400,
  },
  {
    id: 'D14',
    name: 'Comment Thread',
    rootClass: 'comment-thread spreadsheet-comment-thread',
    headerClass: 'comment-thread-header',
    footerClass: 'comment-thread-actions',
    controlClass: 'comment-close-button',
    expectedWidth: 360,
    anchored: true,
  },
  {
    id: 'D15',
    name: 'Delete Sheet Confirmation',
    rootClass: 'sheet-tab-delete-dialog',
    headerClass: 'sheet-tab-delete-header',
    footerClass: 'sheet-tab-delete-footer',
    controlClass: 'sheet-tab-delete-button',
    expectedWidth: 400,
    hasPrimary: false,
  },
  {
    id: 'D16',
    name: 'Help',
    rootClass: 'spreadsheet-help-overlay',
    headerClass: 'spreadsheet-help-overlay-header',
    footerClass: 'spreadsheet-help-overlay-actions',
    controlClass: 'spreadsheet-help-overlay-close',
    expectedWidth: 420,
  },
  {
    id: 'D17',
    name: 'Print Preview',
    rootClass: 'print-preview-overlay spreadsheet-print-preview',
    headerClass: 'print-preview-dialog-header',
    footerClass: 'print-preview-actions',
    controlClass: 'print-preview-button',
    expectedWidth: 680,
  },
]

/** CSS files explicitly owned by D01-D19 in the issue tree. */
export const OWNED_DIALOG_STYLE_PATHS = [
  'features/find-replace-dialog.css',
  'features/find-replace-actions.css',
  'features/find-replace-status-messages.css',
  'features/go-to-dialog.css',
  'features/paste-special-dialog.css',
  'features/text-to-columns-dialog.css',
  'features/remove-duplicates-dialog.css',
  'features/conditional-format-dialog.css',
  'features/data-validation-dialog.css',
  'features/name-manager-dialog.css',
  'features/format-cells-dialog.css',
  'features/number-format-dialog.css',
  'features/page-setup-dialog.css',
  'features/sort-confirmation-dialog.css',
  'features/protection-unlock-dialog.css',
  'features/comment-thread.css',
  'features/sheet-tab-delete-dialog.css',
  'features/menu-help-dialog.css',
  'features/print-preview-dialog.css',
  'features/filter-dropdown.css',
  'styles/toolbar-popovers.css',
] as const
