/** Public compatibility facade for the Sheet Tabs domain. */
export type {
  ActivateSheetTabInput,
  BeginSheetTabRenameCommandInput,
  BeginSheetTabRenameInput,
  BeginSheetTabReorderInput,
  CommitSheetTabRenameCommandInput,
  CommitSheetTabRenameInput,
  CommitSheetTabReorderCommandInput,
  CommitSheetTabReorderInput,
  InitializeSheetTabsInput,
  OpenSheetTabContextMenuInput,
  ReorderSheetMetadataInput,
  RequestSheetTabDeleteInput,
  SetSheetTabsSheetsInput,
  SheetTabContextMenuState,
  SheetTabDeleteConfirmationState,
  SheetTabInteractionSource,
  SheetTabIntent,
  SheetTabMutationKind,
  SheetTabMutationOutcome,
  SheetTabMutationPhase,
  SheetTabMutationResultState,
  SheetTabMutationState,
  SheetTabRenameState,
  SheetTabReorderState,
  SheetTabsCapabilities,
  SheetTabsPhase,
  SheetTabsSheetState,
  SheetTabsState,
  UpdateSheetTabRenameInput,
  UpdateSheetTabReorderInput,
} from './types'
export { getAdjacentSheetId, normalizeSheetTabDraftName, reorderSheetMetadata } from './metadata'
export {
  applySheetTabIntent,
  createBeginSheetTabRenameIntent,
  createBeginSheetTabReorderIntent,
  createCancelSheetTabRenameIntent,
  createCancelSheetTabReorderIntent,
  createCloseSheetTabContextMenuIntent,
  createCommitSheetTabRenameIntent,
  createCommitSheetTabReorderIntent,
  createOpenSheetTabContextMenuIntent,
  createUpdateSheetTabRenameIntent,
  createUpdateSheetTabReorderIntent,
} from './intents'
export {
  DEFAULT_SHEET_TABS_SHEET_STATE,
  DEFAULT_SHEET_TABS_STATE,
  sheetTabsAtom,
  sheetTabsMutationPendingAtom,
  sheetTabsSheetStateAtom,
  sheetTabsSheetsAtom,
} from './state'
export {
  activateSheetTabAtom,
  dispatchSheetTabIntentAtom,
  patchSheetTabsSheetNameAtom,
  setSheetTabsSheetsAtom,
} from './basic-commands'
export { disposeSheetTabsAtom, initializeSheetTabsAtom } from './initialize-command'
export {
  addSheetTabAtom,
  beginSheetTabRenameAtom,
  cancelSheetTabDeleteAtom,
  commitSheetTabRenameAtom,
  commitSheetTabReorderAtom,
  confirmSheetTabDeleteAtom,
  requestSheetTabDeleteAtom,
} from './mutation-commands'
