import { atom } from '@einfach/core'
import type { Getter, Setter } from '@einfach/core'
import type { DisplayCell } from '../backend/types'
import { EMPTY_CELLS, EMPTY_KEY_COLUMNS, allColumnsInRange, immutableReadonlySet, lifecycleFor, nextRemoveDuplicatesSessionId, snapshotCells, snapshotRemoveDuplicatesRange } from './domain'
import { activeRemoveDuplicatesMutationAtom, activeRemoveDuplicatesReadAtom, blocksClose, removeDuplicatesCanCloseAtom, removeDuplicatesCanEditAtom, removeDuplicatesCapabilityStateAtom, removeDuplicatesCellsStateAtom, removeDuplicatesComparisonStateAtom, removeDuplicatesErrorStateAtom, removeDuplicatesExcludeHeaderStateAtom, removeDuplicatesKeyColumnsStateAtom, removeDuplicatesLifecycleAtom, removeDuplicatesLifecycleStateAtom, removeDuplicatesOpenStateAtom, removeDuplicatesRangeStateAtom, removeDuplicatesRangeAtom, removeDuplicatesSessionSequenceStateAtom, removeDuplicatesSessionStateAtom } from './state'
import type { RemoveDuplicatesCapabilityState, RemoveDuplicatesControllerPort, RemoveDuplicatesIntent, RemoveDuplicatesRange } from './types'

export function closeSession(get: Getter, set: Setter): void { const activeRead = get(activeRemoveDuplicatesReadAtom); const activeMutation = get(activeRemoveDuplicatesMutationAtom); const nextSessionId = nextRemoveDuplicatesSessionId(get(removeDuplicatesSessionSequenceStateAtom)); if (nextSessionId !== null) set(removeDuplicatesSessionSequenceStateAtom, nextSessionId); const sessionId = nextSessionId ?? get(removeDuplicatesSessionSequenceStateAtom); set(removeDuplicatesOpenStateAtom, false); set(removeDuplicatesRangeStateAtom, null); set(removeDuplicatesCellsStateAtom, EMPTY_CELLS); set(removeDuplicatesKeyColumnsStateAtom, EMPTY_KEY_COLUMNS); set(removeDuplicatesSessionStateAtom, null); set(removeDuplicatesErrorStateAtom, ''); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('closed', sessionId, null)); if (activeRead !== null) set(activeRemoveDuplicatesReadAtom, null); else if (activeMutation !== null) set(activeRemoveDuplicatesMutationAtom, null) }
export const closeRemoveDuplicatesAtom = atom(null, (get, set): boolean => { if (!get(removeDuplicatesCanCloseAtom)) return false; closeSession(get, set); return true })
closeRemoveDuplicatesAtom.debugLabel = 'spreadsheet.removeDuplicates.close.command'
export const captureRemoveDuplicatesCapabilityAtom = atom(null, (_get, set, source: RemoveDuplicatesControllerPort): RemoveDuplicatesCapabilityState => { let canRead = false; let canRemove = false; try { canRead = typeof source?.readRangeProjection === 'function'; canRemove = typeof source?.removeRowsExact === 'function' } catch { canRead = false; canRemove = false }; const capability = Object.freeze({ canRead, canRemove }); set(removeDuplicatesCapabilityStateAtom, capability); return capability })
captureRemoveDuplicatesCapabilityAtom.debugLabel = 'spreadsheet.removeDuplicates.captureCapability'
export const dispatchRemoveDuplicatesIntentAtom = atom(null, (get, set, intent: RemoveDuplicatesIntent): boolean => { if (!get(removeDuplicatesCanEditAtom)) return false; const range = get(removeDuplicatesRangeAtom); if (range === null) return false; switch (intent.kind) { case 'toggle-key-column': { if (!Number.isSafeInteger(intent.column) || intent.column < range.startCol || intent.column > range.endCol) return false; const next = new Set(get(removeDuplicatesKeyColumnsStateAtom)); if (next.has(intent.column)) next.delete(intent.column); else next.add(intent.column); set(removeDuplicatesKeyColumnsStateAtom, immutableReadonlySet(next)); return true } case 'select-all-key-columns': set(removeDuplicatesKeyColumnsStateAtom, allColumnsInRange(range)); return true; case 'deselect-all-key-columns': set(removeDuplicatesKeyColumnsStateAtom, EMPTY_KEY_COLUMNS); return true; case 'set-comparison': set(removeDuplicatesComparisonStateAtom, intent.comparison); return true; case 'set-exclude-header': set(removeDuplicatesExcludeHeaderStateAtom, intent.excludeHeader); return true } })
dispatchRemoveDuplicatesIntentAtom.debugLabel = 'spreadsheet.removeDuplicates.dispatchIntent'
export const toggleKeyColumnAtom = atom(null, (_get, set, column: number): boolean => set(dispatchRemoveDuplicatesIntentAtom, { kind: 'toggle-key-column', column }))
export const selectAllKeyColumnsAtom = atom(null, (_get, set): boolean => set(dispatchRemoveDuplicatesIntentAtom, { kind: 'select-all-key-columns' }))
export const deselectAllKeyColumnsAtom = atom(null, (_get, set): boolean => set(dispatchRemoveDuplicatesIntentAtom, { kind: 'deselect-all-key-columns' }))
export const openRemoveDuplicatesAtom = atom(null, (get, set, range: RemoveDuplicatesRange, cells: readonly DisplayCell[]): number | null => { const lifecycle = get(removeDuplicatesLifecycleAtom); if (get(activeRemoveDuplicatesReadAtom) !== null || get(activeRemoveDuplicatesMutationAtom) !== null || lifecycle.status === 'read-pending' || blocksClose(lifecycle.status)) return null; const sessionId = nextRemoveDuplicatesSessionId(get(removeDuplicatesSessionSequenceStateAtom)); if (sessionId === null) return null; const rangeSnapshot = snapshotRemoveDuplicatesRange(range); set(removeDuplicatesSessionSequenceStateAtom, sessionId); set(removeDuplicatesSessionStateAtom, null); set(removeDuplicatesRangeStateAtom, rangeSnapshot); set(removeDuplicatesCellsStateAtom, snapshotCells(cells)); set(removeDuplicatesKeyColumnsStateAtom, allColumnsInRange(rangeSnapshot)); set(removeDuplicatesErrorStateAtom, ''); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('editing', sessionId, null)); set(removeDuplicatesOpenStateAtom, true); return sessionId })
openRemoveDuplicatesAtom.debugLabel = 'spreadsheet.removeDuplicates.open.compatibility'
