import { atom } from '@einfach/core'
import { resolveContentMutationAtom } from '../editing/mutation-gateway'
import { acquireHistoryProducerReservationAtom, pushReservedHistoryAtom, releaseHistoryProducerReservationAtom } from '../history'
import type { HistoryLocalReplayPayload } from '../history'
import { applyViewportFilterHiddenStructuralShiftAtom } from '../viewport/effective-hidden'
import { applyViewportFreezeStructuralShiftAtom, getViewportFreezeForSheet, VIEWPORT_FREEZE_REPLAY_KEY, viewportFreezeAtom } from '../viewport/freeze'
import { applyViewportHiddenStructuralShiftAtom, getHiddenColumnsForSheet, getHiddenRowsForSheet, VIEWPORT_HIDDEN_REPLAY_KEY, viewportHiddenAtom } from '../viewport/hidden'
import { DEFAULT_REMOVE_DUPLICATES_TIMEOUT_MS, REMOVE_DUPLICATES_HISTORY_BUSY_ERROR, REMOVE_DUPLICATES_REFRESH_ERROR_PREFIX, REMOVE_DUPLICATES_REMOVE_CAPABILITY_ERROR } from './constants'
import { errorMessage, lifecycleFor, nextRemoveDuplicatesMutationRequestId, normalizeRemoveDuplicatesTimeout, validRevision, withRemoveDuplicatesTimeout } from './domain'
import { canonicalRows, descendingRowDeleteShifts, markMutationStaleBeforeTransport, markOutcomeUnknown, mutationTicketAuthorityIsCurrent, mutationTicketIsCurrent, refreshAcknowledgedMutation, sessionAuthorityIsCurrent, snapshotAcknowledgement, snapshotCellRangeValue, targetKeyFor, targetRangeFor } from './mutation-domain'
import { activeRemoveDuplicatesMutationAtom, removeDuplicatesCapabilityAtom, removeDuplicatesCapabilityStateAtom, removeDuplicatesErrorStateAtom, removeDuplicatesLifecycleAtom, removeDuplicatesLifecycleStateAtom, removeDuplicatesMutationSequenceStateAtom, removeDuplicatesOpenAtom, removeDuplicatesPreviewAtom, removeDuplicatesSessionAtom } from './state'
import type { RemoveDuplicatesMutationTicket } from './state'
import type { RemoveDuplicatesControllerPort, RemoveDuplicatesMutationOutcome, RemoveDuplicatesMutationTarget, RemoveRowsExactRequest, RunRemoveDuplicatesConfirmInput } from './types'

export const runRemoveDuplicatesConfirmAtom = atom(null, async (get, set, input: RunRemoveDuplicatesConfirmInput): Promise<RemoveDuplicatesMutationOutcome> => {
  const active = get(activeRemoveDuplicatesMutationAtom); const lifecycle = get(removeDuplicatesLifecycleAtom)
  if (active !== null) {
    if (active.acknowledgement !== null && lifecycle.status === 'refresh-failed') {
      if (!mutationTicketIsCurrent(get, active)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, active)) return markOutcomeUnknown(set, active)
      let retrySessionId: number | undefined; let refreshProjection: RunRemoveDuplicatesConfirmInput['refreshProjection'] | undefined; let timeoutMs = DEFAULT_REMOVE_DUPLICATES_TIMEOUT_MS; let captureFailed = false
      try { retrySessionId = input.sessionId; refreshProjection = input.refreshProjection; timeoutMs = normalizeRemoveDuplicatesTimeout(input.timeoutMs) } catch { captureFailed = true }
      if (get(activeRemoveDuplicatesMutationAtom) !== active || get(removeDuplicatesLifecycleAtom) !== lifecycle || !mutationTicketIsCurrent(get, active) || !mutationTicketAuthorityIsCurrent(get, active)) return 'stale'
      if (captureFailed || retrySessionId !== active.sessionId || typeof refreshProjection !== 'function') { if (captureFailed) set(removeDuplicatesErrorStateAtom, `${REMOVE_DUPLICATES_REFRESH_ERROR_PREFIX}Invalid retry transport input.`); return captureFailed ? 'refresh-failed' : 'stale' }
      const retryTicket: RemoveDuplicatesMutationTicket = Object.freeze({ ...active, refreshProjection, timeoutMs }); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('refreshing', active.sessionId, active.target.sheetId, null, active.target.requestId)); set(activeRemoveDuplicatesMutationAtom, retryTicket); return refreshAcknowledgedMutation(get, set, retryTicket)
    }
    return lifecycle.status === 'outcome-unknown' ? 'outcome-unknown' : 'stale'
  }
  const session = get(removeDuplicatesSessionAtom)
  if (session === null || !get(removeDuplicatesOpenAtom) || lifecycle.status !== 'editing' || lifecycle.sessionId !== session.sessionId) return 'stale'
  if (!sessionAuthorityIsCurrent(get, session)) { set(removeDuplicatesErrorStateAtom, 'The selected range changed while Remove Duplicates was loading. Retry from the current selection.'); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('read-stale', session.sessionId, session.sheetId, lifecycle.readRequestId)); return 'stale' }
  const initialOpen = get(removeDuplicatesOpenAtom)
  let source: RemoveDuplicatesControllerPort | undefined; let capturedSessionId: number | undefined; let execute: RemoveDuplicatesControllerPort['removeRowsExact']; let refreshProjection: RunRemoveDuplicatesConfirmInput['refreshProjection'] | undefined; let timeoutMs = DEFAULT_REMOVE_DUPLICATES_TIMEOUT_MS; let captureFailed = false
  try { source = input.source; capturedSessionId = input.sessionId; refreshProjection = input.refreshProjection; timeoutMs = normalizeRemoveDuplicatesTimeout(input.timeoutMs); execute = source?.removeRowsExact } catch { captureFailed = true }
  if (get(activeRemoveDuplicatesMutationAtom) !== null || get(removeDuplicatesLifecycleAtom) !== lifecycle || get(removeDuplicatesSessionAtom) !== session || get(removeDuplicatesOpenAtom) !== initialOpen || !sessionAuthorityIsCurrent(get, session)) return 'stale'
  if (captureFailed) { set(removeDuplicatesCapabilityStateAtom, Object.freeze({ ...get(removeDuplicatesCapabilityAtom), canRemove: false })); set(removeDuplicatesErrorStateAtom, REMOVE_DUPLICATES_REMOVE_CAPABILITY_ERROR); return 'blocked' }
  if (capturedSessionId !== session.sessionId) return 'stale'
  if (typeof execute !== 'function' || source === undefined) { set(removeDuplicatesCapabilityStateAtom, Object.freeze({ ...get(removeDuplicatesCapabilityAtom), canRemove: false })); set(removeDuplicatesErrorStateAtom, REMOVE_DUPLICATES_REMOVE_CAPABILITY_ERROR); return 'blocked' }
  if (typeof refreshProjection !== 'function') return 'blocked'
  const preview = get(removeDuplicatesPreviewAtom); const rows = preview === null ? null : canonicalRows(preview.duplicateRows); const targetRange = rows === null ? null : targetRangeFor(session.range, rows)
  if (preview === null || preview.noKeyColumns || rows === null || rows.length === 0 || targetRange === null || !validRevision(session.projectionRevision)) return 'blocked'
  const resolution = set(resolveContentMutationAtom, { kind: 'remove-rows', sheetId: session.sheetId, range: targetRange })
  if (get(activeRemoveDuplicatesMutationAtom) !== null || get(removeDuplicatesLifecycleAtom) !== lifecycle || get(removeDuplicatesSessionAtom) !== session || !sessionAuthorityIsCurrent(get, session)) return 'stale'
  if (resolution.status === 'blocked') { set(removeDuplicatesErrorStateAtom, resolution.diagnostic.message); return 'blocked' }
  const resolvedRanges = resolution.ranges; const resolvedTargetRange = resolvedRanges?.length === 1 ? snapshotCellRangeValue(resolvedRanges[0]) : null
  if (resolvedTargetRange === null) return 'blocked'
  const requestId = nextRemoveDuplicatesMutationRequestId(get(removeDuplicatesMutationSequenceStateAtom))
  if (requestId === null) { set(removeDuplicatesErrorStateAtom, 'Remove Duplicates request identity space is exhausted.'); return 'blocked' }
  const target: RemoveDuplicatesMutationTarget = Object.freeze({ requestId, sheetId: session.sheetId, targetRange: resolvedTargetRange, removedRowIndices: rows, projectionRevision: session.projectionRevision, targetKey: targetKeyFor(session.sheetId, resolvedTargetRange, session.projectionRevision, rows) })
  const request: RemoveRowsExactRequest = Object.freeze({ kind: 'remove-rows', requestId, sheetId: target.sheetId, targetRange: target.targetRange, rows: target.removedRowIndices, revision: target.projectionRevision })
  if (get(activeRemoveDuplicatesMutationAtom) !== null || get(removeDuplicatesLifecycleAtom) !== lifecycle || get(removeDuplicatesSessionAtom) !== session || !sessionAuthorityIsCurrent(get, session)) return 'stale'
  const historyReservation = set(acquireHistoryProducerReservationAtom)
  if (historyReservation === null) { if (get(activeRemoveDuplicatesMutationAtom) === null && get(removeDuplicatesLifecycleAtom) === lifecycle && get(removeDuplicatesSessionAtom) === session && sessionAuthorityIsCurrent(get, session)) set(removeDuplicatesErrorStateAtom, REMOVE_DUPLICATES_HISTORY_BUSY_ERROR); return 'blocked' }
  const ticket: RemoveDuplicatesMutationTicket = Object.freeze({ sessionId: session.sessionId, selectionWitness: session.selectionWitness, workspaceActiveSheetWitness: session.workspaceActiveSheetWitness, target, request, historyReservation, acknowledgement: null, source, execute, refreshProjection, timeoutMs, readRequestId: lifecycle.readRequestId })
  if (get(activeRemoveDuplicatesMutationAtom) !== null || get(removeDuplicatesLifecycleAtom) !== lifecycle || get(removeDuplicatesSessionAtom) !== session || !sessionAuthorityIsCurrent(get, session)) { set(releaseHistoryProducerReservationAtom, historyReservation); return 'stale' }
  set(removeDuplicatesMutationSequenceStateAtom, requestId); set(removeDuplicatesErrorStateAtom, ''); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('mutation-pending', session.sessionId, session.sheetId, null, requestId)); set(activeRemoveDuplicatesMutationAtom, ticket)
  await Promise.resolve(); if (!mutationTicketIsCurrent(get, ticket)) { set(releaseHistoryProducerReservationAtom, ticket.historyReservation); return 'stale' }; if (!mutationTicketAuthorityIsCurrent(get, ticket)) return markMutationStaleBeforeTransport(get, set, ticket, ticket.readRequestId); set(removeDuplicatesLifecycleStateAtom, get(removeDuplicatesLifecycleAtom))
  let acknowledgement: unknown
  try { acknowledgement = await withRemoveDuplicatesTimeout(Reflect.apply(ticket.execute, ticket.source, [ticket.request]), ticket.timeoutMs, 'Remove Duplicates mutation') } catch (error) { const detail = errorMessage(error); if (!mutationTicketIsCurrent(get, ticket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, ticket)) return markOutcomeUnknown(set, ticket); return markOutcomeUnknown(set, ticket, `Backend detail: ${detail}`) }
  if (!mutationTicketIsCurrent(get, ticket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, ticket)) return markOutcomeUnknown(set, ticket)
  const exactAcknowledgement = snapshotAcknowledgement(acknowledgement, ticket)
  if (!mutationTicketIsCurrent(get, ticket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, ticket)) return markOutcomeUnknown(set, ticket); if (exactAcknowledgement === null) return markOutcomeUnknown(set, ticket)
  const acknowledgedTicket: RemoveDuplicatesMutationTicket = Object.freeze({ ...ticket, acknowledgement: exactAcknowledgement }); set(activeRemoveDuplicatesMutationAtom, acknowledgedTicket)
  if (!mutationTicketIsCurrent(get, acknowledgedTicket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, acknowledgedTicket)) return markOutcomeUnknown(set, acknowledgedTicket)
  const mutatedSheetId = ticket.target.sheetId; const freezeBefore = getViewportFreezeForSheet(get(viewportFreezeAtom), mutatedSheetId); const hiddenStateBefore = get(viewportHiddenAtom); const hiddenRowsBefore = getHiddenRowsForSheet(hiddenStateBefore, mutatedSheetId); const hiddenColsBefore = getHiddenColumnsForSheet(hiddenStateBefore, mutatedSheetId)
  for (const shift of descendingRowDeleteShifts(ticket.target.removedRowIndices)) { set(applyViewportFreezeStructuralShiftAtom, { sheetId: mutatedSheetId, shift }); if (!mutationTicketIsCurrent(get, acknowledgedTicket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, acknowledgedTicket)) return markOutcomeUnknown(set, acknowledgedTicket); set(applyViewportHiddenStructuralShiftAtom, { sheetId: mutatedSheetId, shift }); if (!mutationTicketIsCurrent(get, acknowledgedTicket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, acknowledgedTicket)) return markOutcomeUnknown(set, acknowledgedTicket); set(applyViewportFilterHiddenStructuralShiftAtom, { sheetId: mutatedSheetId, shift }); if (!mutationTicketIsCurrent(get, acknowledgedTicket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, acknowledgedTicket)) return markOutcomeUnknown(set, acknowledgedTicket) }
  const localSidePayloads: HistoryLocalReplayPayload[] = []; const freezeAfter = getViewportFreezeForSheet(get(viewportFreezeAtom), mutatedSheetId)
  if ((freezeBefore === null) !== (freezeAfter === null) || (freezeBefore !== null && freezeAfter !== null && (freezeBefore.rows !== freezeAfter.rows || freezeBefore.cols !== freezeAfter.cols))) localSidePayloads.push({ applyKey: VIEWPORT_FREEZE_REPLAY_KEY, sheetId: mutatedSheetId, before: freezeBefore, after: freezeAfter })
  const hiddenStateAfter = get(viewportHiddenAtom); const hiddenRowsAfter = getHiddenRowsForSheet(hiddenStateAfter, mutatedSheetId); const hiddenColsAfter = getHiddenColumnsForSheet(hiddenStateAfter, mutatedSheetId)
  if (hiddenRowsBefore.length !== hiddenRowsAfter.length || !hiddenRowsBefore.every((value, index) => value === hiddenRowsAfter[index]) || hiddenColsBefore.length !== hiddenColsAfter.length || !hiddenColsBefore.every((value, index) => value === hiddenColsAfter[index])) localSidePayloads.push({ applyKey: VIEWPORT_HIDDEN_REPLAY_KEY, sheetId: mutatedSheetId, before: { rows: [...hiddenRowsBefore], cols: [...hiddenColsBefore] }, after: { rows: [...hiddenRowsAfter], cols: [...hiddenColsAfter] } })
  if (!mutationTicketIsCurrent(get, acknowledgedTicket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, acknowledgedTicket)) return markOutcomeUnknown(set, acknowledgedTicket)
  if (exactAcknowledgement.historyRecorded) { const historyRecorded = set(pushReservedHistoryAtom, { reservation: ticket.historyReservation, entry: { transactionId: `remove-duplicates-${ticket.sessionId}-${ticket.target.requestId}`, kind: 'row.delete', sheetId: ticket.target.sheetId, projectionRevision: exactAcknowledgement.revision, affectedRange: { rowStart: exactAcknowledgement.affectedRange.startRow, rowEnd: exactAcknowledgement.affectedRange.endRow, colStart: exactAcknowledgement.affectedRange.startCol, colEnd: exactAcknowledgement.affectedRange.endCol }, ...(localSidePayloads.length > 0 ? { localSidePayloads } : {}) } }); if (!mutationTicketIsCurrent(get, acknowledgedTicket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, acknowledgedTicket)) return markOutcomeUnknown(set, acknowledgedTicket); if (!historyRecorded) return markOutcomeUnknown(set, acknowledgedTicket, 'The acknowledged mutation could not be recorded in history.') }
  if (!mutationTicketIsCurrent(get, acknowledgedTicket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, acknowledgedTicket)) return markOutcomeUnknown(set, acknowledgedTicket); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('local-acknowledged', ticket.sessionId, ticket.target.sheetId, null, ticket.target.requestId)); await Promise.resolve(); if (!mutationTicketIsCurrent(get, acknowledgedTicket)) return 'stale'; if (!mutationTicketAuthorityIsCurrent(get, acknowledgedTicket)) return markOutcomeUnknown(set, acknowledgedTicket); return refreshAcknowledgedMutation(get, set, acknowledgedTicket)
})
runRemoveDuplicatesConfirmAtom.debugLabel = 'spreadsheet.removeDuplicates.confirm'
