import { atom } from '@einfach/core'
import { primarySelectionRegionAtom, selectionAuthorityWitnessAtom, selectionRangeAtom } from '../selection'
import { workspaceActiveSheetAuthorityWitnessAtom, workspaceSessionAtom } from '../workspace'
import { DEFAULT_REMOVE_DUPLICATES_TIMEOUT_MS, REMOVE_DUPLICATES_READ_CAPABILITY_ERROR, REMOVE_DUPLICATES_READ_FAILED_ERROR, REMOVE_DUPLICATES_READ_STALE_ERROR } from './constants'
import { EMPTY_CELLS, allColumnsInRange, errorMessage, lifecycleFor, nextRemoveDuplicatesReadRequestId, nextRemoveDuplicatesSessionId, normalizeRemoveDuplicatesTimeout, sameRange, snapshotRange, toRemoveDuplicatesRange, validRange, withRemoveDuplicatesTimeout } from './domain'
import { blocksClose, activeRemoveDuplicatesMutationAtom, activeRemoveDuplicatesReadAtom, removeDuplicatesCapabilityStateAtom, removeDuplicatesCellsStateAtom, removeDuplicatesErrorStateAtom, removeDuplicatesKeyColumnsStateAtom, removeDuplicatesLifecycleAtom, removeDuplicatesLifecycleStateAtom, removeDuplicatesOpenAtom, removeDuplicatesOpenStateAtom, removeDuplicatesRangeStateAtom, removeDuplicatesReadSequenceStateAtom, removeDuplicatesSessionSequenceStateAtom, removeDuplicatesSessionStateAtom } from './state'
import type { RemoveDuplicatesReadTicket } from './state'
import { classifyReadAcknowledgement, markReadStale, readTicketAuthorityIsCurrent, readTicketContextIsCurrent } from './read-domain'
import type { OpenRemoveDuplicatesInput, RemoveDuplicatesControllerPort, RemoveDuplicatesReadOutcome, RemoveDuplicatesSessionSnapshot } from './types'

export const openRemoveDuplicatesFromSelectionAtom = atom(null, async (get, set, input: OpenRemoveDuplicatesInput): Promise<RemoveDuplicatesReadOutcome> => {
  const lifecycle = get(removeDuplicatesLifecycleAtom); const initialActiveRead = get(activeRemoveDuplicatesReadAtom)
  if (initialActiveRead !== null || lifecycle.status === 'read-pending' || get(activeRemoveDuplicatesMutationAtom) !== null || blocksClose(lifecycle.status)) return 'blocked'
  const sessionId = nextRemoveDuplicatesSessionId(get(removeDuplicatesSessionSequenceStateAtom)); const requestId = nextRemoveDuplicatesReadRequestId(get(removeDuplicatesReadSequenceStateAtom)); const range = snapshotRange(get(selectionRangeAtom)); const selectionWitness = get(selectionAuthorityWitnessAtom); const selectionSheetId = get(primarySelectionRegionAtom).sheetId; const workspaceActiveSheetWitness = get(workspaceActiveSheetAuthorityWitnessAtom); const workspaceActiveSheetId = get(workspaceSessionAtom).activeSheetId; const initialOpen = get(removeDuplicatesOpenAtom)
  let source: RemoveDuplicatesControllerPort | undefined; let compatibilitySheetId: string | undefined; let execute: RemoveDuplicatesControllerPort['readRangeProjection']; let removeExecute: RemoveDuplicatesControllerPort['removeRowsExact']; let timeoutMs = DEFAULT_REMOVE_DUPLICATES_TIMEOUT_MS; let captureFailed = false
  try { source = input.source; compatibilitySheetId = input.sheetId; timeoutMs = normalizeRemoveDuplicatesTimeout(input.timeoutMs); execute = source?.readRangeProjection; removeExecute = source?.removeRowsExact } catch { captureFailed = true }
  const invocationIsCurrent = get(removeDuplicatesLifecycleAtom) === lifecycle && get(activeRemoveDuplicatesReadAtom) === initialActiveRead && get(activeRemoveDuplicatesMutationAtom) === null && get(removeDuplicatesOpenAtom) === initialOpen && get(selectionAuthorityWitnessAtom) === selectionWitness && get(workspaceActiveSheetAuthorityWitnessAtom) === workspaceActiveSheetWitness && get(primarySelectionRegionAtom).sheetId === selectionSheetId && get(workspaceSessionAtom).activeSheetId === workspaceActiveSheetId && sameRange(get(selectionRangeAtom), range)
  if (!invocationIsCurrent) return 'blocked'
  const compatibilitySheetMatches = compatibilitySheetId === undefined || (typeof compatibilitySheetId === 'string' && compatibilitySheetId === selectionSheetId)
  if (captureFailed || sessionId === null || requestId === null || selectionSheetId.length === 0 || selectionSheetId !== workspaceActiveSheetId || !compatibilitySheetMatches || !validRange(range)) { set(removeDuplicatesErrorStateAtom, REMOVE_DUPLICATES_READ_FAILED_ERROR); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('read-failed', lifecycle.sessionId, null)); return 'failed' }
  const canRead = typeof execute === 'function'; const canRemove = typeof removeExecute === 'function'; const removeDuplicatesRange = toRemoveDuplicatesRange(range)
  set(removeDuplicatesCapabilityStateAtom, Object.freeze({ canRead, canRemove })); set(removeDuplicatesSessionSequenceStateAtom, sessionId); set(removeDuplicatesReadSequenceStateAtom, requestId); set(removeDuplicatesSessionStateAtom, null); set(removeDuplicatesRangeStateAtom, removeDuplicatesRange); set(removeDuplicatesCellsStateAtom, EMPTY_CELLS); set(removeDuplicatesKeyColumnsStateAtom, allColumnsInRange(removeDuplicatesRange)); set(removeDuplicatesOpenStateAtom, true); set(removeDuplicatesErrorStateAtom, '')
  if (!canRead || execute === undefined || source === undefined) { set(removeDuplicatesErrorStateAtom, REMOVE_DUPLICATES_READ_CAPABILITY_ERROR); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('read-failed', sessionId, selectionSheetId, requestId)); return 'failed' }
  const request: Readonly<import('../backend/types').RangeProjectionRequest> = Object.freeze({ kind: 'range', sheetId: selectionSheetId, range, requestId, reason: 'selection' })
  const ticket: RemoveDuplicatesReadTicket = Object.freeze({ sessionId, requestId, sheetId: selectionSheetId, range, selectionWitness, workspaceActiveSheetWitness, source, execute, request, timeoutMs })
  set(removeDuplicatesLifecycleStateAtom, lifecycleFor('read-pending', sessionId, ticket.sheetId, requestId)); set(activeRemoveDuplicatesReadAtom, ticket)
  await Promise.resolve(); if (!readTicketContextIsCurrent(get, ticket)) return 'stale'; if (!readTicketAuthorityIsCurrent(get, ticket)) return markReadStale(set, ticket); set(removeDuplicatesLifecycleStateAtom, get(removeDuplicatesLifecycleAtom))
  let acknowledgement: unknown
  try { acknowledgement = await withRemoveDuplicatesTimeout(Reflect.apply(ticket.execute, ticket.source, [ticket.request]), ticket.timeoutMs, 'Remove Duplicates read') } catch (error) { const detail = errorMessage(error); if (!readTicketContextIsCurrent(get, ticket)) return 'stale'; if (!readTicketAuthorityIsCurrent(get, ticket)) return markReadStale(set, ticket); set(removeDuplicatesErrorStateAtom, `${REMOVE_DUPLICATES_READ_FAILED_ERROR} ${detail}`); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('read-failed', sessionId, ticket.sheetId, requestId)); set(activeRemoveDuplicatesReadAtom, null); return 'failed' }
  if (!readTicketContextIsCurrent(get, ticket)) return 'stale'; if (!readTicketAuthorityIsCurrent(get, ticket)) return markReadStale(set, ticket)
  const classification = classifyReadAcknowledgement(acknowledgement, ticket)
  if (!readTicketContextIsCurrent(get, ticket)) return 'stale'; if (!readTicketAuthorityIsCurrent(get, ticket)) return markReadStale(set, ticket)
  if (classification.status !== 'exact') { set(removeDuplicatesErrorStateAtom, classification.status === 'stale' ? REMOVE_DUPLICATES_READ_STALE_ERROR : REMOVE_DUPLICATES_READ_FAILED_ERROR); set(removeDuplicatesLifecycleStateAtom, lifecycleFor(classification.status === 'stale' ? 'read-stale' : 'read-failed', sessionId, ticket.sheetId, requestId)); set(activeRemoveDuplicatesReadAtom, null); return classification.status }
  const exactAcknowledgement = classification.acknowledgement; const rangeSnapshot = toRemoveDuplicatesRange(exactAcknowledgement.range); const session: RemoveDuplicatesSessionSnapshot = Object.freeze({ sessionId, sheetId: exactAcknowledgement.sheetId, range: rangeSnapshot, selectionWitness: ticket.selectionWitness, workspaceActiveSheetWitness: ticket.workspaceActiveSheetWitness, projectionRevision: exactAcknowledgement.revision, cells: exactAcknowledgement.cells })
  set(removeDuplicatesSessionStateAtom, session); set(removeDuplicatesRangeStateAtom, session.range); set(removeDuplicatesCellsStateAtom, session.cells); set(removeDuplicatesKeyColumnsStateAtom, allColumnsInRange(session.range)); set(removeDuplicatesErrorStateAtom, ''); set(removeDuplicatesLifecycleStateAtom, lifecycleFor('editing', sessionId, ticket.sheetId, requestId)); set(activeRemoveDuplicatesReadAtom, null); return 'editing'
})
openRemoveDuplicatesFromSelectionAtom.debugLabel = 'spreadsheet.removeDuplicates.openFromSelection'
export const retryRemoveDuplicatesReadAtom = openRemoveDuplicatesFromSelectionAtom
