import { expect, test, type Page } from '@playwright/test'
import { select } from '../support/clipboard'

const cell = (page: Page, coord: string) => page.locator(`td[data-cell="${coord}"]`)
const grid = (page: Page) => page.locator('[data-workbook-grid]')
async function visibility(page: Page, action: string) {
  const menu = page.getByRole('combobox', { name: 'Row and column visibility' })
  await menu.selectOption(action)
  await expect(menu).toBeEnabled()
  await expect(menu).toHaveValue('')
}
async function locate(page: Page, address: string) {
  const name = page.getByRole('textbox', { name: 'Name box' })
  await name.fill(address)
  await name.press('Enter')
}
test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await expect(cell(page, '1:0')).toHaveText('SO-10001')
})

test('hidden rows collapse without gaps, navigation skips them and undo restores seed data', async ({ page }) => {
  await select(page, 'A3:A5', '2:0')
  await visibility(page, 'hide-rows')
  for (const row of [2, 3, 4]) await expect(cell(page, `${row}:0`)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Select row 3', exact: true })).toHaveCount(0)
  const before = await cell(page, '1:0').boundingBox()
  const after = await cell(page, '5:0').boundingBox()
  expect(Math.abs(after!.y - before!.y - before!.height)).toBeLessThan(1)
  await select(page, 'A2', '1:0')
  await grid(page).press('ArrowDown')
  await expect(page.getByRole('textbox', { name: 'Name box' })).toHaveValue('A6')
  await grid(page).press('ArrowUp')
  await expect(page.getByRole('textbox', { name: 'Name box' })).toHaveValue('A2')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '2:0')).toHaveText('SO-10002')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(cell(page, '2:0')).toHaveCount(0)
})

test('hidden columns collapse and cell editor stays aligned after arrow and Tab navigation', async ({ page }) => {
  await select(page, 'B2:D2', '1:1')
  await visibility(page, 'hide-columns')
  for (const col of [1, 2, 3]) await expect(cell(page, `1:${col}`)).toHaveCount(0)
  const a = await cell(page, '1:0').boundingBox()
  const e = await cell(page, '1:4').boundingBox()
  expect(Math.abs(e!.x - a!.x - a!.width)).toBeLessThan(1)
  await select(page, 'A2', '1:0')
  await grid(page).press('Tab')
  await expect(page.getByRole('textbox', { name: 'Name box' })).toHaveValue('E2')
  await grid(page).press('F2')
  const editor = page.getByRole('textbox', { name: 'Cell editor' })
  await expect(editor).toBeVisible()
  const editorBox = await editor.boundingBox()
  expect(Math.abs(editorBox!.x - e!.x)).toBeLessThanOrEqual(2)
  await editor.fill('8')
  await editor.press('Enter')
  await expect(cell(page, '1:4')).toHaveText('8')
  await expect(cell(page, '1:6')).toHaveText('632')
  await visibility(page, 'unhide-all')
  await expect(cell(page, '1:1')).toHaveText('Acme Co.')
})

test('Summary original hidden examples are native and unhide keeps original sizes', async ({ page }) => {
  await page.getByRole('tab', { name: 'Summary', exact: true }).click()
  await expect(cell(page, '0:0')).toHaveText('First order total')
  await expect(cell(page, '9:0')).toHaveCount(0)
  await expect(cell(page, '0:6')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
  await visibility(page, 'unhide-all')
  await expect(cell(page, '9:0')).toHaveText('Hidden row example')
  await expect(cell(page, '0:6')).toHaveText('Hidden column example')
  const size = await cell(page, '0:0').boundingBox()
  expect(size!.width).toBe(200)
  expect(size!.height).toBe(40)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '9:0')).toHaveCount(0)
  await expect(cell(page, '0:6')).toHaveCount(0)
})

test('unhide selected range preserves unrelated hidden rows and columns', async ({ page }) => {
  await select(page, 'B3:D5', '2:1')
  await visibility(page, 'hide-rows')
  await locate(page, 'B3:D5')
  await visibility(page, 'hide-columns')
  await locate(page, 'C4')
  await visibility(page, 'unhide')
  await expect(cell(page, '3:2')).toHaveText('East')
  for (const coord of ['2:2', '4:2', '3:1', '3:3']) await expect(cell(page, coord)).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '3:2')).toHaveCount(0)
})

test('all hidden axes remain recoverable from the toolbar', async ({ page }) => {
  await page.getByRole('button', { name: 'Select all cells' }).click()
  await visibility(page, 'hide-rows')
  await expect(page.locator('td[data-cell]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Select all cells' }).click()
  await visibility(page, 'hide-columns')
  await expect(page.getByRole('columnheader')).toHaveCount(0)
  await visibility(page, 'unhide-all')
  await select(page, 'A2', '1:0')
  await expect(cell(page, '1:0')).toHaveText('SO-10001')
})

test('hidden final rows and columns keep boundary keys and PageDown inside visible data', async ({ page }) => {
  await locate(page, 'A990:P1001')
  await visibility(page, 'hide-rows')
  await locate(page, 'O1:P1')
  await visibility(page, 'hide-columns')
  await select(page, 'A2', '1:0')
  await grid(page).press('ControlOrMeta+ArrowDown')
  await expect(page.getByRole('textbox', { name: 'Name box' })).toHaveValue('A989')
  await expect(cell(page, '988:0')).toBeInViewport()
  await grid(page).press('ControlOrMeta+ArrowRight')
  await expect(page.getByRole('textbox', { name: 'Name box' })).toHaveValue('N989')
  await expect(cell(page, '988:13')).toBeInViewport()
  await grid(page).press('PageDown')
  await expect(page.getByRole('textbox', { name: 'Name box' })).toHaveValue('N989')
})

test('visibility stays on its sheet through switching and mixed history', async ({ page }) => {
  await select(page, 'B2', '1:1')
  await visibility(page, 'hide-columns')
  await page.getByRole('tab', { name: 'Summary', exact: true }).click()
  await expect(cell(page, '0:1')).toHaveText('79')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell(page, '0:1')).toHaveText('79')
  await page.getByRole('tab', { name: 'Sales Orders', exact: true }).click()
  await expect(cell(page, '1:1')).toHaveText('Acme Co.')
})
