import type { Getter } from '@einfach/core'
import { selectionAuthorityWitnessAtom, selectionSnapshotAtom } from '../selection'
import { workspaceActiveSheetAuthorityWitnessAtom, workspaceSessionAtom } from '../workspace'
import type { FilterSortEntrypointTarget } from './types'
import type { FilterSortEntrypointTicket, FilterSortMutationTicket } from './internal-types'
import { filterDropdownBackingAtom, filterSortDraftBackingAtom, filterSortLifecycleBackingAtom, filterSortSessionIdBackingAtom } from './state'

export function resolveFilterSortEntrypointTarget(get: Getter): FilterSortEntrypointTarget | null { const selection = get(selectionSnapshotAtom); const activeSheetId = get(workspaceSessionAtom).activeSheetId; const selectionSheetId = selection.activeCell.sheetId; if (selectionSheetId && activeSheetId && selectionSheetId !== activeSheetId) return null; const sheetId = selectionSheetId || activeSheetId; const colIndex = selection.activeCell.col; return !sheetId || !Number.isSafeInteger(colIndex) || colIndex < 0 ? null : Object.freeze({ sheetId, colIndex }) }
export const sameFilterSortTarget = (left: FilterSortEntrypointTarget | null, right: FilterSortEntrypointTarget | null): boolean => left?.sheetId === right?.sheetId && left?.colIndex === right?.colIndex
export function mutationTicketAuthorityIsCurrent(get: Getter, ticket: FilterSortMutationTicket): boolean { const dropdown = get(filterDropdownBackingAtom); const draft = get(filterSortDraftBackingAtom); const lifecycle = get(filterSortLifecycleBackingAtom); return dropdown.status === 'open' && dropdown.sheetId === ticket.sheetId && dropdown.colIndex === ticket.colIndex && get(filterSortSessionIdBackingAtom) === ticket.sessionId && draft.sessionId === ticket.sessionId && draft.sheetId === ticket.sheetId && draft.colIndex === ticket.colIndex && lifecycle.sessionId === ticket.sessionId && lifecycle.sheetId === ticket.sheetId && lifecycle.colIndex === ticket.colIndex && lifecycle.requestId === ticket.requestId }
export function entrypointTicketAuthorityIsCurrent(get: Getter, ticket: FilterSortEntrypointTicket): boolean { if (get(workspaceActiveSheetAuthorityWitnessAtom) !== ticket.workspaceWitness) return false; return ticket.targetAuthority === 'explicit' || (ticket.selectionWitness !== null && get(selectionAuthorityWitnessAtom) === ticket.selectionWitness && sameFilterSortTarget(resolveFilterSortEntrypointTarget(get), ticket.target)) }
