import type { ProjectionRequestId, SortRangeRequest } from '../backend/types'
import type { CellRange } from '../shared'
import type { HistoryEntry, HistoryProducerReservation } from '../history'
import type { SelectionAuthorityWitness } from '../selection'
import type { WorkspaceActiveSheetAuthorityWitness } from '../workspace'
import type { FilterSortControllerPort, FilterSortEntrypoint, FilterSortEntrypointTarget, FilterSortState, FilterSortStateBySheet, PhysicalSortControllerPort, ReapplyFilterInput, RunFilterSortMutationInput, RunPhysicalSortInput, SortDirection } from './types'

export interface FilterSortStateStore { readonly stateBySheet: FilterSortStateBySheet; readonly insertionOrder: readonly string[] }
export interface FilterSortMutationTicket { readonly sessionId: number; readonly requestId: ProjectionRequestId; readonly sheetId: string; readonly colIndex: number; readonly next: FilterSortState; readonly request: import('./types').SetFilterSortRequest; readonly sourceWitness: FilterSortControllerPort; readonly transport: NonNullable<FilterSortControllerPort['setFilterSort']>; readonly refreshProjection: RunFilterSortMutationInput['refreshProjection']; readonly timeoutMs: number; readonly historyReservation: HistoryProducerReservation }
export interface FilterSortEntrypointTicketBase { readonly operationId: number; readonly requestId: ProjectionRequestId; readonly entrypoint: FilterSortEntrypoint; readonly target: FilterSortEntrypointTarget; readonly direction: SortDirection | null; readonly attempt: number; readonly selectionWitness: SelectionAuthorityWitness | null; readonly workspaceWitness: WorkspaceActiveSheetAuthorityWitness; readonly targetAuthority: 'selection' | 'explicit'; readonly refreshProjection: ReapplyFilterInput['refreshProjection'] | RunPhysicalSortInput['refreshProjection']; readonly timeoutMs: number; readonly historyReservation: HistoryProducerReservation }
export interface ReapplyFilterTicket extends FilterSortEntrypointTicketBase { readonly kind: 'reapply-filter'; readonly direction: null; readonly targetAuthority: 'selection'; readonly selectionWitness: SelectionAuthorityWitness; readonly next: FilterSortState; readonly request: import('./types').SetFilterSortRequest; readonly sourceWitness: FilterSortControllerPort; readonly transport: NonNullable<FilterSortControllerPort['setFilterSort']> }
export interface PhysicalSortTicket extends FilterSortEntrypointTicketBase { readonly kind: 'physical-sort'; readonly direction: SortDirection; readonly request: SortRangeRequest; readonly sourceWitness: PhysicalSortControllerPort; readonly transport: NonNullable<PhysicalSortControllerPort['sortRange']> }
export type FilterSortEntrypointTicket = ReapplyFilterTicket | PhysicalSortTicket
export type BoundedOperationResult<T> = { readonly kind: 'fulfilled'; readonly value: T } | { readonly kind: 'rejected'; readonly error: unknown } | { readonly kind: 'timeout' }
export type FilterSortAcknowledgementSnapshot = { readonly kind: 'matched'; readonly sheetId: string; readonly requestId: ProjectionRequestId; readonly historyRecorded: boolean; readonly revision: HistoryEntry['projectionRevision']; readonly hiddenRowIndices: readonly number[] } | { readonly kind: 'invalid' }
export type PhysicalSortAcknowledgement = { readonly kind: 'applied'; readonly movedRows: number; readonly revision: HistoryEntry['projectionRevision']; readonly affectedRange: CellRange } | { readonly kind: 'rejected'; readonly code: import('../backend/types').SortRangeRejectionCode; readonly message?: string; readonly anchor?: string } | { readonly kind: 'invalid' }
