import { atom } from '@einfach/core'
import { acquireHistoryProducerReservationAtom, releaseHistoryProducerReservationAtom } from '../history'
import { setViewportFilterHiddenRowsAtom } from '../viewport/effective-hidden'
import type { FilterSortControllerPort, RunFilterSortMutationInput, SetFilterSortRequest } from './types'
import { FILTER_SORT_ACKNOWLEDGEMENT_ERROR, FILTER_SORT_CAPABILITY_ERROR, FILTER_SORT_INVALID_INPUT_ERROR, FILTER_SORT_PENDING_ERROR, FILTER_SORT_REFRESH_TIMEOUT_ERROR, FILTER_SORT_STALE_OPERATION_ERROR, FILTER_SORT_TRANSPORT_TIMEOUT_ERROR } from './constants'
import { mutationTicketAuthorityIsCurrent } from './authority-domain'
import { classifyFilterSortAcknowledgement, recordFilterSortHistory } from './acknowledgement-domain'
import { activeFilterSortEntrypointAtom, activeFilterSortMutationAtom, filterSortCapabilityBackingAtom, filterSortDraftBackingAtom, filterSortErrorBackingAtom, filterSortLifecycleBackingAtom, filterSortStateBackingAtom, filterSortSyncTicketBackingAtom } from './state'
import { filterDropdownAtom, filterSortDraftAtom, filterSortLifecycleAtom, filterSortStateAtom, filterSortSyncTicketAtom } from './projection-atoms'
import { EMPTY_FILTER_SORT_STATE, deriveMutationState, draftFromState, errorMessage, lifecycleFor, nextFilterSortRequestId, normalizeState, outcomeUnknownError, refreshFailureError, runBoundedOperation, snapshotTimeoutMs, stateStoreWith } from './value-domain'
import type { FilterSortMutationTicket } from './internal-types'

type Captured = { readonly kind: 'captured'; readonly sourceWitness: FilterSortControllerPort; readonly transport: FilterSortControllerPort['setFilterSort']; readonly sessionId: number; readonly intent: RunFilterSortMutationInput['intent']; readonly refreshProjection: RunFilterSortMutationInput['refreshProjection']; readonly timeoutMs: number } | { readonly kind: 'invalid' }
function capture(input: RunFilterSortMutationInput): Captured { try { const sourceWitness = input.source; const sessionId = input.sessionId; const intentKind = input.intent?.kind; const refreshProjection = input.refreshProjection; const timeoutMs = snapshotTimeoutMs(input.timeoutMs); if (!Number.isSafeInteger(sessionId) || typeof refreshProjection !== 'function' || timeoutMs === null || !['clear-filter', 'clear-column', 'apply-draft'].includes(intentKind)) return Object.freeze({ kind: 'invalid' }); let transport: FilterSortControllerPort['setFilterSort']; try { transport = sourceWitness?.setFilterSort } catch {} return Object.freeze({ kind: 'captured', sourceWitness, transport, sessionId, intent: Object.freeze({ kind: intentKind }) as RunFilterSortMutationInput['intent'], refreshProjection, timeoutMs }) } catch { return Object.freeze({ kind: 'invalid' }) } }
export const runFilterSortMutationAtom = atom(null, async (get, set, input: RunFilterSortMutationInput): Promise<void> => {
 if (get(activeFilterSortMutationAtom) !== null || get(activeFilterSortEntrypointAtom) !== null) return; const captured = capture(input); if (get(activeFilterSortMutationAtom) !== null || get(activeFilterSortEntrypointAtom) !== null) return; const dropdown = get(filterDropdownAtom); const draft = get(filterSortDraftAtom); const lifecycle = get(filterSortLifecycleAtom); if (captured.kind === 'invalid') { set(filterSortErrorBackingAtom, FILTER_SORT_INVALID_INPUT_ERROR); set(filterSortLifecycleBackingAtom, lifecycleFor('blocked', draft.sessionId, draft.sheetId, draft.colIndex)); return }
 if (dropdown.status !== 'open' || captured.sessionId !== draft.sessionId || lifecycle.sessionId !== draft.sessionId || dropdown.sheetId !== draft.sheetId || dropdown.colIndex !== draft.colIndex || ['pending', 'local-acknowledged', 'refreshing'].includes(lifecycle.status)) return
 if (typeof captured.transport !== 'function') { set(filterSortCapabilityBackingAtom, false); set(filterSortErrorBackingAtom, FILTER_SORT_CAPABILITY_ERROR); set(filterSortLifecycleBackingAtom, lifecycleFor('blocked', draft.sessionId, draft.sheetId, draft.colIndex)); return } set(filterSortCapabilityBackingAtom, true)
 const sheetId = draft.sheetId; const colIndex = draft.colIndex; if (sheetId === null || colIndex === null) return; const derived = deriveMutationState(get(filterSortStateAtom)[sheetId] ?? EMPTY_FILTER_SORT_STATE, draft, captured.intent); if (derived.state === null) { set(filterSortErrorBackingAtom, derived.error ?? FILTER_SORT_INVALID_INPUT_ERROR); set(filterSortLifecycleBackingAtom, lifecycleFor('blocked', draft.sessionId, sheetId, colIndex)); return } const requestId = nextFilterSortRequestId(get(filterSortSyncTicketAtom)); if (requestId === null) { set(filterSortErrorBackingAtom, 'Filter and sort request identity space is exhausted.'); set(filterSortLifecycleBackingAtom, lifecycleFor('blocked', draft.sessionId, sheetId, colIndex)); return }
 const next = normalizeState(derived.state); const request: SetFilterSortRequest = Object.freeze({ kind: 'set-filter-sort', sheetId, rules: next.rules, requestId, recordHistory: true }); const historyReservation = set(acquireHistoryProducerReservationAtom); if (historyReservation === null) { set(filterSortErrorBackingAtom, FILTER_SORT_PENDING_ERROR); set(filterSortLifecycleBackingAtom, lifecycleFor('blocked', draft.sessionId, sheetId, colIndex)); return }
 const ticket: FilterSortMutationTicket = Object.freeze({ sessionId: draft.sessionId, requestId, sheetId, colIndex, next, request, sourceWitness: captured.sourceWitness, transport: captured.transport, refreshProjection: captured.refreshProjection, timeoutMs: captured.timeoutMs, historyReservation }); set(filterSortSyncTicketBackingAtom, requestId); set(activeFilterSortMutationAtom, ticket); set(filterSortErrorBackingAtom, ''); set(filterSortLifecycleBackingAtom, lifecycleFor('pending', ticket.sessionId, sheetId, colIndex, requestId)); const owns = () => get(activeFilterSortMutationAtom) === ticket; const authority = () => mutationTicketAuthorityIsCurrent(get, ticket); const unknown = (detail: string) => { if (!owns()) return; set(filterSortErrorBackingAtom, outcomeUnknownError(detail)); set(filterSortLifecycleBackingAtom, lifecycleFor('outcome-unknown', ticket.sessionId, sheetId, colIndex, requestId)) }; const releaseUnsent = () => { if (!owns()) return; if (!set(releaseHistoryProducerReservationAtom, ticket.historyReservation)) { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return } if (!owns()) return; set(filterSortErrorBackingAtom, FILTER_SORT_STALE_OPERATION_ERROR); set(filterSortLifecycleBackingAtom, lifecycleFor('blocked', ticket.sessionId, sheetId, colIndex)); set(activeFilterSortMutationAtom, null) }
 await Promise.resolve(); if (!owns()) return; if (!authority()) { releaseUnsent(); return } set(filterSortLifecycleBackingAtom, get(filterSortLifecycleAtom)); const transport = await runBoundedOperation(() => ticket.transport.call(ticket.sourceWitness, ticket.request), ticket.timeoutMs); if (!owns()) return; if (!authority()) { unknown(FILTER_SORT_STALE_OPERATION_ERROR); return } if (transport.kind === 'timeout') { unknown(FILTER_SORT_TRANSPORT_TIMEOUT_ERROR); return } if (transport.kind === 'rejected') { unknown(errorMessage(transport.error)); return } const acknowledgement = classifyFilterSortAcknowledgement(transport.value, sheetId, requestId, { expectedHistoryRecorded: null, allowAbsentHiddenRowIndices: false }); if (!owns()) return; if (!authority()) { unknown(FILTER_SORT_STALE_OPERATION_ERROR); return } if (acknowledgement.kind === 'invalid') { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return } if (!recordFilterSortHistory(set, acknowledgement, sheetId, ticket.historyReservation)) { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return } if (!owns()) return; if (!authority()) { unknown(FILTER_SORT_STALE_OPERATION_ERROR); return }
 set(filterSortStateBackingAtom, stateStoreWith(get(filterSortStateBackingAtom), sheetId, ticket.next)); set(setViewportFilterHiddenRowsAtom, { sheetId, rows: acknowledgement.hiddenRowIndices }); set(filterSortDraftBackingAtom, draftFromState(ticket.sessionId, sheetId, colIndex, ticket.next, get(filterSortDraftAtom).availableValues)); set(filterSortLifecycleBackingAtom, lifecycleFor('local-acknowledged', ticket.sessionId, sheetId, colIndex, requestId)); await Promise.resolve(); if (!owns()) return; if (!authority()) { unknown(FILTER_SORT_STALE_OPERATION_ERROR); return } set(filterSortLifecycleBackingAtom, lifecycleFor('refreshing', ticket.sessionId, sheetId, colIndex, requestId)); const refresh = await runBoundedOperation(() => ticket.refreshProjection(sheetId), ticket.timeoutMs); if (!owns()) return; if (!authority()) { unknown(FILTER_SORT_STALE_OPERATION_ERROR); return } if (refresh.kind === 'timeout') { set(filterSortErrorBackingAtom, refreshFailureError(FILTER_SORT_REFRESH_TIMEOUT_ERROR)); set(filterSortLifecycleBackingAtom, lifecycleFor('refresh-failed', ticket.sessionId, sheetId, colIndex, requestId)); return } if (refresh.kind === 'rejected') { set(filterSortErrorBackingAtom, refreshFailureError(refresh.error)); set(filterSortLifecycleBackingAtom, lifecycleFor('refresh-failed', ticket.sessionId, sheetId, colIndex, requestId)); return } if (!set(releaseHistoryProducerReservationAtom, ticket.historyReservation)) { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return } if (!owns()) return; if (!authority()) { unknown(FILTER_SORT_STALE_OPERATION_ERROR); set(activeFilterSortMutationAtom, null); return } set(filterSortErrorBackingAtom, ''); set(filterSortLifecycleBackingAtom, lifecycleFor('editing', ticket.sessionId, sheetId, colIndex)); set(activeFilterSortMutationAtom, null)
}); runFilterSortMutationAtom.debugLabel = 'spreadsheet.filterSort.runMutation'
