import { atom } from '@einfach/core'
import type { Atom, Getter } from '@einfach/core'
import type { CellRange } from '../shared'
import type { ProjectionRequestId, SortRangeRejectionCode } from '../backend/types'
import { getHiddenRowsForSheet, viewportHiddenAtom } from '../viewport/hidden'
import { getFilterHiddenRowsForSheet, viewportFilterHiddenAtom } from '../viewport/effective-hidden'
import type { FilterSortEntrypointTarget, PhysicalSortControllerPort, PhysicalSortDiagnostic, PhysicalSortDiagnosticCode, RunPhysicalSortInput } from './types'
import { PHYSICAL_SORT_CAPABILITY_ERROR } from './constants'
import { filterSortStateAtom } from './projection-atoms'
import type { PhysicalSortAcknowledgement } from './internal-types'
import { isValidProjectionRevision } from './acknowledgement-domain'
import { snapshotTimeoutMs } from './value-domain'

export const PHYSICAL_SORT_REJECTION_MESSAGES: Readonly<Record<PhysicalSortDiagnosticCode, string>> = Object.freeze({ unsupported: PHYSICAL_SORT_CAPABILITY_ERROR, 'invalid-range': 'Sort could not run: the sort range is invalid.', 'empty-keys': 'Sort could not run: no sort column was provided.', 'key-out-of-range': 'Sort could not run: the sort column is outside the sorted range.', 'spill-in-range': 'Sort could not run: the range overlaps a spilled array. Move or clear the array first.', 'invalid-payload': 'Sort could not run: the sort request was malformed.', 'source-too-large': 'Sort could not run: the range is too large to sort.', 'merge-in-range': 'Sort could not run: the range contains merged cells. Unmerge them before sorting.' })
export const physicalSortRejectionMessage = (code: PhysicalSortDiagnosticCode, fallback?: string): string => PHYSICAL_SORT_REJECTION_MESSAGES[code] ?? fallback ?? 'Sort could not run.'
export const sortRangeCapabilityBackingAtom = atom(false); sortRangeCapabilityBackingAtom.debugLabel = 'spreadsheet.sort.capabilityBacking'
export const sortRangeSupportedAtom: Atom<boolean> = atom((get) => get(sortRangeCapabilityBackingAtom)); sortRangeSupportedAtom.debugLabel = 'spreadsheet.sort.supported'
function readSortRangePort(source: PhysicalSortControllerPort): PhysicalSortControllerPort['sortRange'] { try { const port = source?.sortRange; return typeof port === 'function' ? port : undefined } catch { return undefined } }
export const captureSortRangeCapabilityAtom = atom(null, (_get, set, source: PhysicalSortControllerPort) => set(sortRangeCapabilityBackingAtom, readSortRangePort(source) !== undefined)); captureSortRangeCapabilityAtom.debugLabel = 'spreadsheet.sort.captureCapability'
export const physicalSortDiagnosticBackingAtom = atom<PhysicalSortDiagnostic | null>(null); physicalSortDiagnosticBackingAtom.debugLabel = 'spreadsheet.sort.diagnosticBacking'
export const physicalSortDiagnosticAtom: Atom<PhysicalSortDiagnostic | null> = atom((get) => get(physicalSortDiagnosticBackingAtom)); physicalSortDiagnosticAtom.debugLabel = 'spreadsheet.sort.diagnostic'
export const clearPhysicalSortDiagnosticAtom = atom(null, (_get, set) => set(physicalSortDiagnosticBackingAtom, null)); clearPhysicalSortDiagnosticAtom.debugLabel = 'spreadsheet.sort.clearDiagnostic'
export type CapturedPhysicalSortRange = { readonly kind: 'range'; readonly value: CellRange } | { readonly kind: 'absent' } | { readonly kind: 'invalid' }
export type CapturedPhysicalSortTarget = { readonly kind: 'selection' } | { readonly kind: 'explicit'; readonly value: FilterSortEntrypointTarget } | { readonly kind: 'invalid' }
export type CapturedRunPhysicalSortInput = { readonly kind: 'captured'; readonly sourceWitness: PhysicalSortControllerPort; readonly transport: PhysicalSortControllerPort['sortRange']; readonly entrypoint: RunPhysicalSortInput['entrypoint']; readonly direction: RunPhysicalSortInput['direction']; readonly range: CapturedPhysicalSortRange; readonly target: CapturedPhysicalSortTarget; readonly refreshProjection: RunPhysicalSortInput['refreshProjection']; readonly timeoutMs: number | null } | { readonly kind: 'invalid' }
export function captureRunPhysicalSortInput(input: RunPhysicalSortInput): CapturedRunPhysicalSortInput { try { const sourceWitness = input.source; let transport: PhysicalSortControllerPort['sortRange']; try { transport = sourceWitness?.sortRange } catch {}; const entrypoint = input.entrypoint; const direction = input.direction; const rangeValue = input.range; const targetValue = input.target; const refreshProjection = input.refreshProjection; const timeoutMs = snapshotTimeoutMs(input.timeoutMs); let range: CapturedPhysicalSortRange; if (rangeValue === null) range = Object.freeze({ kind: 'absent' }); else if (typeof rangeValue !== 'object') range = Object.freeze({ kind: 'invalid' }); else { const { rowStart, rowEnd, colStart, colEnd } = rangeValue; range = !Number.isSafeInteger(rowStart) || !Number.isSafeInteger(rowEnd) || !Number.isSafeInteger(colStart) || !Number.isSafeInteger(colEnd) ? Object.freeze({ kind: 'invalid' }) : Object.freeze({ kind: 'range', value: Object.freeze({ rowStart: Math.min(rowStart, rowEnd), rowEnd: Math.max(rowStart, rowEnd), colStart: Math.min(colStart, colEnd), colEnd: Math.max(colStart, colEnd) }) }) }; let target: CapturedPhysicalSortTarget; if (targetValue === undefined) target = Object.freeze({ kind: 'selection' }); else if (typeof targetValue !== 'object' || targetValue === null) target = Object.freeze({ kind: 'invalid' }); else { const { sheetId, colIndex } = targetValue; target = typeof sheetId === 'string' && sheetId.length > 0 && Number.isSafeInteger(colIndex) && colIndex >= 0 ? Object.freeze({ kind: 'explicit', value: Object.freeze({ sheetId, colIndex }) }) : Object.freeze({ kind: 'invalid' }) }; return Object.freeze({ kind: 'captured', sourceWitness, transport, entrypoint, direction, range, target, refreshProjection, timeoutMs }) } catch { return Object.freeze({ kind: 'invalid' }) } }
export const isValidSortRange = (range: CellRange): boolean => Number.isSafeInteger(range.rowStart) && Number.isSafeInteger(range.rowEnd) && Number.isSafeInteger(range.colStart) && Number.isSafeInteger(range.colEnd) && range.rowStart >= 0 && range.colStart >= 0 && range.rowEnd >= range.rowStart && range.colEnd >= range.colStart
const sheetHasRules = (get: Getter, sheetId: string): boolean => (get(filterSortStateAtom)[sheetId]?.rules.length ?? 0) > 0
const isRejectionCode = (value: unknown): value is SortRangeRejectionCode => ['invalid-range', 'empty-keys', 'key-out-of-range', 'spill-in-range', 'invalid-payload', 'source-too-large', 'merge-in-range'].includes(value as string)
const sameRange = (left: CellRange, right: CellRange) => left.rowStart === right.rowStart && left.rowEnd === right.rowEnd && left.colStart === right.colStart && left.colEnd === right.colEnd
export function classifyPhysicalSortAcknowledgement(value: unknown, sheetId: string, requestId: ProjectionRequestId, requestedRange: CellRange): PhysicalSortAcknowledgement { try { if (typeof value !== 'object' || value === null || Array.isArray(value)) return { kind: 'invalid' }; const result = value as Record<PropertyKey, unknown>; if (result.sheetId !== sheetId || result.requestId !== requestId) return { kind: 'invalid' }; if (result.applied === false) { const { code, message, anchor } = result; return result.kind !== 'sort-range-not-applied' || !isRejectionCode(code) || (message !== undefined && typeof message !== 'string') || (anchor !== undefined && typeof anchor !== 'string') ? { kind: 'invalid' } : Object.freeze({ kind: 'rejected', code, ...(message === undefined ? {} : { message }), ...(anchor === undefined ? {} : { anchor }) }) }; const { movedRows, movedCells, affectedRange, revision } = result; if (result.applied !== true || result.kind !== 'sort-range' || !Number.isSafeInteger(movedRows) || (movedRows as number) < 0 || !Number.isSafeInteger(movedCells) || (movedCells as number) < 0 || typeof affectedRange !== 'object' || affectedRange === null) return { kind: 'invalid' }; const fields = affectedRange as Record<PropertyKey, unknown>; const { rowStart, rowEnd, colStart, colEnd } = fields; if (!Number.isSafeInteger(rowStart) || !Number.isSafeInteger(rowEnd) || !Number.isSafeInteger(colStart) || !Number.isSafeInteger(colEnd)) return { kind: 'invalid' }; const range: CellRange = Object.freeze({ rowStart: rowStart as number, rowEnd: rowEnd as number, colStart: colStart as number, colEnd: colEnd as number }); return !isValidSortRange(range) || !sameRange(range, requestedRange) || !isValidProjectionRevision(revision) ? { kind: 'invalid' } : Object.freeze({ kind: 'applied', movedRows: movedRows as number, revision, affectedRange: range }) } catch { return { kind: 'invalid' } }
}
export function buildSortExcludedRows(get: Getter, sheetId: string, range: CellRange): number[] { const excluded = new Set<number>(); const clip = (rows: readonly number[]) => { for (const row of rows) if (row >= range.rowStart && row <= range.rowEnd) excluded.add(row) }; clip(getHiddenRowsForSheet(get(viewportHiddenAtom), sheetId)); if (sheetHasRules(get, sheetId)) clip(getFilterHiddenRowsForSheet(get(viewportFilterHiddenAtom), sheetId)); return [...excluded].sort((a, b) => a - b) }
