import { atom } from '@einfach/core'
import { acquireHistoryProducerReservationAtom, pushReservedHistoryAtom, releaseHistoryProducerReservationAtom } from '../history'
import { selectionAuthorityWitnessAtom } from '../selection'
import { workspaceActiveSheetAuthorityWitnessAtom } from '../workspace'
import type { RunPhysicalSortInput } from './types'
import { FILTER_SORT_ACKNOWLEDGEMENT_ERROR, FILTER_SORT_PENDING_ERROR, FILTER_SORT_REFRESH_TIMEOUT_ERROR, FILTER_SORT_STALE_OPERATION_ERROR, FILTER_SORT_TRANSPORT_TIMEOUT_ERROR } from './constants'
import { entrypointTicketAuthorityIsCurrent, resolveFilterSortEntrypointTarget } from './authority-domain'
import { activeFilterSortEntrypointAtom, activeFilterSortMutationAtom, filterSortEntrypointOperationIdStateAtom, filterSortEntrypointStateBackingAtom, filterSortSyncTicketBackingAtom } from './state'
import { filterDropdownAtom, filterSortSyncTicketAtom } from './projection-atoms'
import { buildSortExcludedRows, captureRunPhysicalSortInput, classifyPhysicalSortAcknowledgement, isValidSortRange, physicalSortDiagnosticBackingAtom, physicalSortRejectionMessage, sortRangeCapabilityBackingAtom } from './physical-sort-domain'
import { entrypointStateFor, entrypointStateForTicket, errorMessage, nextEntrypointAttempt, nextFilterSortOperationId, nextFilterSortRequestId, outcomeUnknownError, refreshFailureError, runBoundedOperation } from './value-domain'
import type { PhysicalSortTicket } from './internal-types'

export const runPhysicalSortAtom = atom(null, async (get, set, input: RunPhysicalSortInput): Promise<void> => {
 if (get(activeFilterSortEntrypointAtom) !== null || get(activeFilterSortMutationAtom) !== null || get(filterDropdownAtom).status === 'open') return; const captured = captureRunPhysicalSortInput(input); if (get(activeFilterSortEntrypointAtom) !== null || get(activeFilterSortMutationAtom) !== null) return; if (captured.kind === 'invalid') { const message = physicalSortRejectionMessage('invalid-payload'); set(physicalSortDiagnosticBackingAtom, Object.freeze({ code: 'invalid-payload', message })); set(filterSortEntrypointStateBackingAtom, entrypointStateFor('blocked', { attempt: 1, error: message })); return }
 const available = typeof captured.transport === 'function'; set(sortRangeCapabilityBackingAtom, available); const explicit = captured.target.kind === 'explicit' ? captured.target.value : null; const target = captured.target.kind === 'selection' ? resolveFilterSortEntrypointTarget(get) : explicit; const range = captured.range.kind === 'range' ? captured.range.value : null; const rangeValid = range !== null && isValidSortRange(range); const columnInRange = rangeValid && target !== null && target.colIndex >= range!.colStart && target.colIndex <= range!.colEnd; const directionValid = captured.direction === 'asc' || captured.direction === 'desc'; const entrypointValid = captured.entrypoint === 'toolbar' || captured.entrypoint === 'menu-bar'; const payloadValid = captured.target.kind !== 'invalid' && captured.range.kind !== 'invalid' && typeof captured.refreshProjection === 'function' && captured.timeoutMs !== null; const rejection = !available ? 'unsupported' : !payloadValid || !directionValid || !entrypointValid ? 'invalid-payload' : target === null ? 'empty-keys' : !rangeValid ? 'invalid-range' : !columnInRange ? 'key-out-of-range' : null
 if (rejection !== null || typeof captured.transport !== 'function' || target === null || range === null || captured.timeoutMs === null) { const code = rejection ?? 'invalid-range'; const message = physicalSortRejectionMessage(code); set(physicalSortDiagnosticBackingAtom, Object.freeze({ code, message })); set(filterSortEntrypointStateBackingAtom, entrypointStateFor('blocked', { entrypoint: entrypointValid ? captured.entrypoint : null, target, direction: directionValid ? captured.direction : null, attempt: 1, error: message })); return }
 const operationId = nextFilterSortOperationId(get(filterSortEntrypointOperationIdStateAtom)); const requestId = nextFilterSortRequestId(get(filterSortSyncTicketAtom)); if (operationId === null || requestId === null) { set(filterSortEntrypointStateBackingAtom, entrypointStateFor('blocked', { entrypoint: captured.entrypoint, target, direction: captured.direction, attempt: 1, error: 'Filter and sort command identity space is exhausted.' })); return }; const request = Object.freeze({ kind: 'sort-range' as const, sheetId: target.sheetId, range, keys: Object.freeze([Object.freeze({ col: target.colIndex, direction: captured.direction })]), excludedRows: Object.freeze(buildSortExcludedRows(get, target.sheetId, range)), requestId }); const attempt = nextEntrypointAttempt(get(filterSortEntrypointStateBackingAtom), captured.entrypoint, target, captured.direction); const targetAuthority = captured.target.kind === 'explicit' ? 'explicit' as const : 'selection' as const; const reservation = set(acquireHistoryProducerReservationAtom); if (reservation === null) { set(filterSortEntrypointStateBackingAtom, entrypointStateFor('blocked', { entrypoint: captured.entrypoint, target, direction: captured.direction, attempt: 1, error: FILTER_SORT_PENDING_ERROR })); return }
 const ticket: PhysicalSortTicket = Object.freeze({ kind: 'physical-sort', operationId, requestId, entrypoint: captured.entrypoint, target, direction: captured.direction, attempt, request, sourceWitness: captured.sourceWitness, transport: captured.transport, refreshProjection: captured.refreshProjection, timeoutMs: captured.timeoutMs, selectionWitness: targetAuthority === 'selection' ? get(selectionAuthorityWitnessAtom) : null, workspaceWitness: get(workspaceActiveSheetAuthorityWitnessAtom), targetAuthority, historyReservation: reservation }); set(filterSortEntrypointOperationIdStateAtom, operationId); set(filterSortSyncTicketBackingAtom, requestId); set(activeFilterSortEntrypointAtom, ticket); set(physicalSortDiagnosticBackingAtom, null); set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('pending', ticket)); const owns = () => get(activeFilterSortEntrypointAtom) === ticket; const authority = () => entrypointTicketAuthorityIsCurrent(get, ticket); const unknown = (detail: string) => { if (owns()) set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('outcome-unknown', ticket, outcomeUnknownError(detail))) }; const markUnknown = (detail: string) => set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('outcome-unknown', ticket, outcomeUnknownError(detail))); const releaseUnsent = () => { if (!owns()) return; if (!set(releaseHistoryProducerReservationAtom, ticket.historyReservation)) { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return }; if (!owns()) return; set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('stale', ticket, FILTER_SORT_STALE_OPERATION_ERROR)); set(activeFilterSortEntrypointAtom, null) }
 await Promise.resolve(); if (!owns()) return; if (!authority()) { releaseUnsent(); return }; set(filterSortEntrypointStateBackingAtom, get(filterSortEntrypointStateBackingAtom)); const transport = await runBoundedOperation(() => ticket.transport.call(ticket.sourceWitness, ticket.request), ticket.timeoutMs); if (!owns()) return; if (transport.kind === 'timeout') { unknown(FILTER_SORT_TRANSPORT_TIMEOUT_ERROR); return }; if (transport.kind === 'rejected') { set(activeFilterSortEntrypointAtom, null); markUnknown(errorMessage(transport.error)); return }; const acknowledgement = classifyPhysicalSortAcknowledgement(transport.value, ticket.request.sheetId, ticket.requestId, ticket.request.range); if (!owns()) return; if (acknowledgement.kind === 'invalid') { markUnknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return }; if (acknowledgement.kind === 'rejected') { if (!set(releaseHistoryProducerReservationAtom, ticket.historyReservation)) { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return }; if (!owns()) return; const message = physicalSortRejectionMessage(acknowledgement.code, acknowledgement.message); set(physicalSortDiagnosticBackingAtom, Object.freeze({ code: acknowledgement.code, message, ...(acknowledgement.anchor === undefined ? {} : { anchor: acknowledgement.anchor }) })); set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('error', ticket, message)); set(activeFilterSortEntrypointAtom, null); return }
 if (acknowledgement.movedRows > 0 && !set(pushReservedHistoryAtom, { reservation: ticket.historyReservation, entry: { transactionId: `range-sort-${ticket.target.sheetId}-${ticket.requestId}`, kind: 'range.sort', sheetId: ticket.target.sheetId, projectionRevision: acknowledgement.revision, affectedRange: acknowledgement.affectedRange } })) { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return }; if (!owns()) return; set(physicalSortDiagnosticBackingAtom, null); set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('local-acknowledged', ticket)); await Promise.resolve(); if (!owns()) return; set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('refreshing', ticket)); const refresh = await runBoundedOperation(() => ticket.refreshProjection(ticket.target.sheetId), ticket.timeoutMs); if (!owns()) return; if (refresh.kind === 'timeout') { set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('refresh-failed', ticket, refreshFailureError(FILTER_SORT_REFRESH_TIMEOUT_ERROR))); return }; if (refresh.kind === 'rejected') { set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('refresh-failed', ticket, refreshFailureError(refresh.error))); return }; if (!set(releaseHistoryProducerReservationAtom, ticket.historyReservation)) { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return }; if (!owns()) return; set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('idle', ticket)); set(activeFilterSortEntrypointAtom, null)
}); runPhysicalSortAtom.debugLabel = 'spreadsheet.sort.runPhysical'
