import { atom } from '@einfach/core'
import { acquireHistoryProducerReservationAtom, releaseHistoryProducerReservationAtom } from '../history'
import { setViewportFilterHiddenRowsAtom } from '../viewport/effective-hidden'
import { selectionAuthorityWitnessAtom } from '../selection'
import { workspaceActiveSheetAuthorityWitnessAtom } from '../workspace'
import type { FilterSortControllerPort, ReapplyFilterInput } from './types'
import { FILTER_SORT_ACKNOWLEDGEMENT_ERROR, FILTER_SORT_CAPABILITY_ERROR, FILTER_SORT_DROPDOWN_OPEN_ERROR, FILTER_SORT_PENDING_ERROR, FILTER_SORT_REAPPLY_NO_RULES_ERROR, FILTER_SORT_REFRESH_TIMEOUT_ERROR, FILTER_SORT_STALE_OPERATION_ERROR, FILTER_SORT_TARGET_ERROR, FILTER_SORT_TRANSPORT_TIMEOUT_ERROR } from './constants'
import { classifyFilterSortAcknowledgement } from './acknowledgement-domain'
import { entrypointTicketAuthorityIsCurrent, resolveFilterSortEntrypointTarget } from './authority-domain'
import { activeFilterSortEntrypointAtom, activeFilterSortMutationAtom, filterSortCapabilityBackingAtom, filterSortEntrypointOperationIdStateAtom, filterSortEntrypointStateBackingAtom, filterSortSyncTicketBackingAtom } from './state'
import { filterDropdownAtom, filterSortCapabilityAtom, filterSortStateAtom, filterSortSyncTicketAtom } from './projection-atoms'
import { entrypointStateFor, entrypointStateForTicket, errorMessage, nextEntrypointAttempt, nextFilterSortOperationId, nextFilterSortRequestId, normalizeState, outcomeUnknownError, refreshFailureError, runBoundedOperation, snapshotTimeoutMs } from './value-domain'
import type { ReapplyFilterTicket } from './internal-types'

const hasRules = (get: Parameters<Parameters<typeof atom>[1]>[0], sheetId: string): boolean => { const state = get(filterSortStateAtom)[sheetId]; return state !== undefined && state.rules.length > 0 }
export const reapplyFilterDisabledReasonAtom = atom((get): string | null => { if (!get(filterSortCapabilityAtom)) return FILTER_SORT_CAPABILITY_ERROR; if (get(activeFilterSortMutationAtom) !== null || get(activeFilterSortEntrypointAtom) !== null) return FILTER_SORT_PENDING_ERROR; if (get(filterDropdownAtom).status === 'open') return FILTER_SORT_DROPDOWN_OPEN_ERROR; const target = resolveFilterSortEntrypointTarget(get); return target === null ? FILTER_SORT_TARGET_ERROR : !hasRules(get, target.sheetId) ? FILTER_SORT_REAPPLY_NO_RULES_ERROR : null }); reapplyFilterDisabledReasonAtom.debugLabel = 'spreadsheet.filterSort.reapplyDisabledReason'
type Captured = { kind: 'captured'; sourceWitness: FilterSortControllerPort; transport: FilterSortControllerPort['setFilterSort']; entrypoint: 'toolbar' | 'menu-bar'; refreshProjection: ReapplyFilterInput['refreshProjection']; timeoutMs: number } | { kind: 'invalid' }
function capture(input: ReapplyFilterInput): Captured { try { const sourceWitness = input.source; const entrypoint = input.entrypoint; const refreshProjection = input.refreshProjection; const timeoutMs = snapshotTimeoutMs(input.timeoutMs); if ((entrypoint !== 'toolbar' && entrypoint !== 'menu-bar') || typeof refreshProjection !== 'function' || timeoutMs === null) return Object.freeze({ kind: 'invalid' }); let transport: FilterSortControllerPort['setFilterSort']; try { transport = sourceWitness?.setFilterSort } catch {} return Object.freeze({ kind: 'captured', sourceWitness, transport, entrypoint, refreshProjection, timeoutMs }) } catch { return Object.freeze({ kind: 'invalid' }) } }
export const reapplyFilterAtom = atom(null, async (get, set, input: ReapplyFilterInput): Promise<void> => {
 if (get(activeFilterSortMutationAtom) !== null || get(activeFilterSortEntrypointAtom) !== null) return; const captured = capture(input); if (get(activeFilterSortMutationAtom) !== null || get(activeFilterSortEntrypointAtom) !== null || captured.kind === 'invalid') return; if (typeof captured.transport !== 'function') { set(filterSortCapabilityBackingAtom, false); return } set(filterSortCapabilityBackingAtom, true); if (get(reapplyFilterDisabledReasonAtom) !== null) return; const target = resolveFilterSortEntrypointTarget(get); if (target === null) return; const committed = get(filterSortStateAtom)[target.sheetId]; if (committed === undefined || committed.rules.length === 0) return
 const operationId = nextFilterSortOperationId(get(filterSortEntrypointOperationIdStateAtom)); const requestId = nextFilterSortRequestId(get(filterSortSyncTicketAtom)); if (operationId === null || requestId === null) { set(filterSortEntrypointStateBackingAtom, entrypointStateFor('blocked', { entrypoint: captured.entrypoint, target, attempt: 1, error: 'Filter and sort command identity space is exhausted.' })); return } const next = normalizeState(committed); const request = Object.freeze({ kind: 'set-filter-sort' as const, sheetId: target.sheetId, rules: next.rules, requestId, recordHistory: false }); const attempt = nextEntrypointAttempt(get(filterSortEntrypointStateBackingAtom), captured.entrypoint, target, null); const reservation = set(acquireHistoryProducerReservationAtom); if (reservation === null) { set(filterSortEntrypointStateBackingAtom, entrypointStateFor('blocked', { entrypoint: captured.entrypoint, target, attempt: 1, error: FILTER_SORT_PENDING_ERROR })); return }
 const ticket: ReapplyFilterTicket = Object.freeze({ kind: 'reapply-filter', operationId, requestId, entrypoint: captured.entrypoint, target, direction: null, attempt, next, request, sourceWitness: captured.sourceWitness, transport: captured.transport, refreshProjection: captured.refreshProjection, timeoutMs: captured.timeoutMs, selectionWitness: get(selectionAuthorityWitnessAtom), workspaceWitness: get(workspaceActiveSheetAuthorityWitnessAtom), targetAuthority: 'selection', historyReservation: reservation }); set(filterSortEntrypointOperationIdStateAtom, operationId); set(filterSortSyncTicketBackingAtom, requestId); set(activeFilterSortEntrypointAtom, ticket); set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('pending', ticket)); const owns = () => get(activeFilterSortEntrypointAtom) === ticket; const authority = () => entrypointTicketAuthorityIsCurrent(get, ticket); const stale = () => { if (owns()) set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('stale', ticket, FILTER_SORT_STALE_OPERATION_ERROR)) }; const unknown = (detail: string) => { if (owns()) set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('outcome-unknown', ticket, outcomeUnknownError(detail))) }; const releaseUnsent = () => { if (!owns()) return; if (!set(releaseHistoryProducerReservationAtom, ticket.historyReservation)) { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return } if (!owns()) return; stale(); set(activeFilterSortEntrypointAtom, null) }
 await Promise.resolve(); if (!owns()) return; if (!authority()) { releaseUnsent(); return } set(filterSortEntrypointStateBackingAtom, get(filterSortEntrypointStateBackingAtom)); const transport = await runBoundedOperation(() => ticket.transport.call(ticket.sourceWitness, ticket.request), ticket.timeoutMs); if (!owns()) return; if (!authority()) { stale(); return } if (transport.kind === 'timeout') { unknown(FILTER_SORT_TRANSPORT_TIMEOUT_ERROR); return } if (transport.kind === 'rejected') { unknown(errorMessage(transport.error)); return } const acknowledgement = classifyFilterSortAcknowledgement(transport.value, ticket.target.sheetId, ticket.requestId, { expectedHistoryRecorded: false, allowAbsentHiddenRowIndices: true }); if (!owns()) return; if (!authority()) { stale(); return } if (acknowledgement.kind === 'invalid') { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return } set(setViewportFilterHiddenRowsAtom, { sheetId: ticket.target.sheetId, rows: acknowledgement.hiddenRowIndices }); set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('local-acknowledged', ticket)); await Promise.resolve(); if (!owns()) return; if (!authority()) { stale(); return } set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('refreshing', ticket)); const refresh = await runBoundedOperation(() => ticket.refreshProjection(ticket.target.sheetId), ticket.timeoutMs); if (!owns()) return; if (!authority()) { stale(); return } if (refresh.kind === 'timeout') { set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('refresh-failed', ticket, refreshFailureError(FILTER_SORT_REFRESH_TIMEOUT_ERROR))); return } if (refresh.kind === 'rejected') { set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('refresh-failed', ticket, refreshFailureError(refresh.error))); return } if (!set(releaseHistoryProducerReservationAtom, ticket.historyReservation)) { unknown(FILTER_SORT_ACKNOWLEDGEMENT_ERROR); return } if (!owns()) return; if (!authority()) { stale(); set(activeFilterSortEntrypointAtom, null); return } set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('idle', ticket)); set(activeFilterSortEntrypointAtom, null)
}); reapplyFilterAtom.debugLabel = 'spreadsheet.filterSort.reapply'
