import { atom } from '@einfach/core'
import { releaseHistoryProducerReservationAtom } from '../history'
import type { RetryFilterSortRefreshInput } from './types'
import { FILTER_SORT_ACKNOWLEDGEMENT_ERROR, FILTER_SORT_REFRESH_TIMEOUT_ERROR, FILTER_SORT_STALE_OPERATION_ERROR } from './constants'
import { mutationTicketAuthorityIsCurrent } from './authority-domain'
import { activeFilterSortEntrypointAtom, activeFilterSortMutationAtom, filterSortEntrypointStateBackingAtom, filterSortErrorBackingAtom, filterSortLifecycleBackingAtom } from './state'
import { filterSortLifecycleAtom } from './projection-atoms'
import { entrypointStateForTicket, outcomeUnknownError, refreshFailureError, runBoundedOperation, snapshotTimeoutMs, lifecycleFor } from './value-domain'

type Captured = { readonly kind: 'captured'; readonly refreshProjection: RetryFilterSortRefreshInput['refreshProjection']; readonly timeoutMs: number } | { readonly kind: 'invalid' }
function capture(input: RetryFilterSortRefreshInput): Captured { try { const refreshProjection = input.refreshProjection; const timeoutMs = snapshotTimeoutMs(input.timeoutMs); return typeof refreshProjection !== 'function' || timeoutMs === null ? Object.freeze({ kind: 'invalid' }) : Object.freeze({ kind: 'captured', refreshProjection, timeoutMs }) } catch { return Object.freeze({ kind: 'invalid' }) } }
export const retryFilterSortRefreshAtom = atom(null, async (get, set, input: RetryFilterSortRefreshInput): Promise<void> => {
 const mutation = get(activeFilterSortMutationAtom); const lifecycle = get(filterSortLifecycleAtom); if (mutation !== null && lifecycle.status === 'refresh-failed' && lifecycle.sessionId === mutation.sessionId && lifecycle.requestId === mutation.requestId) { if (!mutationTicketAuthorityIsCurrent(get, mutation)) return; const captured = capture(input); if (get(activeFilterSortMutationAtom) !== mutation || get(filterSortLifecycleAtom) !== lifecycle || !mutationTicketAuthorityIsCurrent(get, mutation) || captured.kind === 'invalid') return; set(filterSortErrorBackingAtom, ''); set(filterSortLifecycleBackingAtom, lifecycleFor('refreshing', mutation.sessionId, mutation.sheetId, mutation.colIndex, mutation.requestId)); if (get(activeFilterSortMutationAtom) !== mutation || !mutationTicketAuthorityIsCurrent(get, mutation)) return; const refresh = await runBoundedOperation(() => captured.refreshProjection(mutation.sheetId), captured.timeoutMs); if (get(activeFilterSortMutationAtom) !== mutation || !mutationTicketAuthorityIsCurrent(get, mutation)) return; if (refresh.kind === 'timeout' || refresh.kind === 'rejected') { set(filterSortErrorBackingAtom, refreshFailureError(refresh.kind === 'timeout' ? FILTER_SORT_REFRESH_TIMEOUT_ERROR : refresh.error)); set(filterSortLifecycleBackingAtom, lifecycleFor('refresh-failed', mutation.sessionId, mutation.sheetId, mutation.colIndex, mutation.requestId)); return }; if (!set(releaseHistoryProducerReservationAtom, mutation.historyReservation)) { set(filterSortErrorBackingAtom, outcomeUnknownError(FILTER_SORT_ACKNOWLEDGEMENT_ERROR)); set(filterSortLifecycleBackingAtom, lifecycleFor('outcome-unknown', mutation.sessionId, mutation.sheetId, mutation.colIndex, mutation.requestId)); return }; if (get(activeFilterSortMutationAtom) !== mutation) return; if (!mutationTicketAuthorityIsCurrent(get, mutation)) { set(filterSortErrorBackingAtom, outcomeUnknownError(FILTER_SORT_STALE_OPERATION_ERROR)); set(filterSortLifecycleBackingAtom, lifecycleFor('outcome-unknown', mutation.sessionId, mutation.sheetId, mutation.colIndex, mutation.requestId)); set(activeFilterSortMutationAtom, null); return }; set(filterSortErrorBackingAtom, ''); set(filterSortLifecycleBackingAtom, lifecycleFor('editing', mutation.sessionId, mutation.sheetId, mutation.colIndex)); set(activeFilterSortMutationAtom, null); return }
 const ticket = get(activeFilterSortEntrypointAtom); const state = get(filterSortEntrypointStateBackingAtom); if (ticket === null || state.status !== 'refresh-failed' || state.operationId !== ticket.operationId || state.requestId !== ticket.requestId) return; const owns = () => get(activeFilterSortEntrypointAtom) === ticket; const captured = capture(input); if (!owns() || get(filterSortEntrypointStateBackingAtom) !== state || captured.kind === 'invalid') return; set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('refreshing', ticket)); if (!owns()) return; const refresh = await runBoundedOperation(() => captured.refreshProjection(ticket.target.sheetId), captured.timeoutMs); if (!owns()) return; if (refresh.kind === 'timeout' || refresh.kind === 'rejected') { set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('refresh-failed', ticket, refreshFailureError(refresh.kind === 'timeout' ? FILTER_SORT_REFRESH_TIMEOUT_ERROR : refresh.error))); return }; if (!set(releaseHistoryProducerReservationAtom, ticket.historyReservation)) { set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('outcome-unknown', ticket, outcomeUnknownError(FILTER_SORT_ACKNOWLEDGEMENT_ERROR))); return }; if (!owns()) return; set(filterSortEntrypointStateBackingAtom, entrypointStateForTicket('idle', ticket)); set(activeFilterSortEntrypointAtom, null)
}); retryFilterSortRefreshAtom.debugLabel = 'spreadsheet.filterSort.retryRefresh'
