import { atom } from '@einfach/core'
import { CLOSED_FILTER_DROPDOWN_STATE, EMPTY_FILTER_SORT_STATE_STORE, INITIAL_FILTER_SORT_DRAFT, INITIAL_FILTER_SORT_ENTRYPOINT_STATE, INITIAL_FILTER_SORT_LIFECYCLE } from './value-domain'
import type { FilterSortMutationTicket, FilterSortEntrypointTicket } from './internal-types'
import type { FilterDropdownState, FilterSortDraftState, FilterSortEntrypointState, FilterSortLifecycleState } from './types'

export const filterSortStateBackingAtom = atom(EMPTY_FILTER_SORT_STATE_STORE); filterSortStateBackingAtom.debugLabel = 'spreadsheet.filterSort.stateBacking'
export const filterDropdownBackingAtom = atom<FilterDropdownState>(CLOSED_FILTER_DROPDOWN_STATE); filterDropdownBackingAtom.debugLabel = 'spreadsheet.filterSort.dropdownBacking'
export const filterSortErrorBackingAtom = atom(''); filterSortErrorBackingAtom.debugLabel = 'spreadsheet.filterSort.errorBacking'
export const filterSortSyncTicketBackingAtom = atom(0); filterSortSyncTicketBackingAtom.debugLabel = 'spreadsheet.filterSort.syncTicketBacking'
export const filterSortSessionIdBackingAtom = atom(0); filterSortSessionIdBackingAtom.debugLabel = 'spreadsheet.filterSort.sessionIdBacking'
export const filterSortCapabilityBackingAtom = atom(false); filterSortCapabilityBackingAtom.debugLabel = 'spreadsheet.filterSort.capabilityBacking'
export const filterSortDraftBackingAtom = atom<FilterSortDraftState>(INITIAL_FILTER_SORT_DRAFT); filterSortDraftBackingAtom.debugLabel = 'spreadsheet.filterSort.draftBacking'
export const filterSortLifecycleBackingAtom = atom<FilterSortLifecycleState>(INITIAL_FILTER_SORT_LIFECYCLE); filterSortLifecycleBackingAtom.debugLabel = 'spreadsheet.filterSort.lifecycleBacking'
export const filterSortEntrypointOperationIdStateAtom = atom(0); filterSortEntrypointOperationIdStateAtom.debugLabel = 'spreadsheet.filterSort.entrypointOperationIdState'
export const filterSortEntrypointStateBackingAtom = atom<FilterSortEntrypointState>(INITIAL_FILTER_SORT_ENTRYPOINT_STATE); filterSortEntrypointStateBackingAtom.debugLabel = 'spreadsheet.filterSort.entrypointStateBacking'
export const activeFilterSortMutationAtom = atom<FilterSortMutationTicket | null>(null); activeFilterSortMutationAtom.debugLabel = 'spreadsheet.filterSort.activeMutation'
export const activeFilterSortEntrypointAtom = atom<FilterSortEntrypointTicket | null>(null); activeFilterSortEntrypointAtom.debugLabel = 'spreadsheet.filterSort.activeEntrypoint'
