import type { ProjectionRequestId } from '../backend/types'
import type { FilterSortDraftState, FilterSortEntrypoint, FilterSortEntrypointState, FilterSortEntrypointTarget, FilterSortLifecycleState, FilterSortState, SortDirection, ColumnFilterRule, RunFilterSortMutationInput } from './types'
import { FILTER_SORT_DEFAULT_TIMEOUT_MS, FILTER_SORT_INVALID_INPUT_ERROR, FILTER_SORT_OUTCOME_UNKNOWN_ERROR, MAX_FILTER_LIST_VALUES, MAX_FILTER_SORT_SHEETS } from './constants'
import type { BoundedOperationResult, FilterSortStateStore } from './internal-types'

export const EMPTY_FILTER_SORT_STATE: FilterSortState = Object.freeze({ rules: Object.freeze([]) })
export const EMPTY_FILTER_SORT_STATE_BY_SHEET = Object.freeze({})
export const EMPTY_FILTER_SORT_STATE_STORE: FilterSortStateStore = Object.freeze({ stateBySheet: EMPTY_FILTER_SORT_STATE_BY_SHEET, insertionOrder: Object.freeze([]) })
export const CLOSED_FILTER_DROPDOWN_STATE = Object.freeze({ status: 'closed' } as const)
export const INITIAL_FILTER_SORT_DRAFT: FilterSortDraftState = Object.freeze({ sessionId: 0, sheetId: null, colIndex: null, searchInput: '', selectedValues: Object.freeze([]), selectionMode: 'all', conditionKind: 'none', equalsInput: '', containsInput: '', rangeMinInput: '', rangeMaxInput: '', availableValues: Object.freeze([]) })
export const INITIAL_FILTER_SORT_LIFECYCLE: FilterSortLifecycleState = Object.freeze({ status: 'closed', sessionId: 0, requestId: null, sheetId: null, colIndex: null })
export const INITIAL_FILTER_SORT_ENTRYPOINT_STATE: FilterSortEntrypointState = Object.freeze({ status: 'idle', operationId: null, requestId: null, entrypoint: null, target: null, direction: null, attempt: 0, error: '' })
export function snapshotTimeoutMs(value: unknown): number | null { return value === undefined ? FILTER_SORT_DEFAULT_TIMEOUT_MS : typeof value === 'number' && Number.isFinite(value) && value > 0 ? value : null }
export function runBoundedOperation<T>(launch: () => Promise<T>, timeoutMs: number): Promise<BoundedOperationResult<T>> { return new Promise((resolve) => { let active = true; const finish = (result: BoundedOperationResult<T>): void => { if (!active) return; active = false; clearTimeout(timer); resolve(Object.freeze(result)) }; const timer = setTimeout(() => finish({ kind: 'timeout' }), timeoutMs); let pending: Promise<T>; try { pending = Promise.resolve(launch()) } catch (error) { finish({ kind: 'rejected', error }); return }; pending.then((value) => finish({ kind: 'fulfilled', value }), (error) => finish({ kind: 'rejected', error })) }) }
export function errorMessage(error: unknown): string { try { if (error instanceof Error && typeof error.message === 'string') return error.message } catch {} try { return String(error) } catch { return 'Unknown filter and sort transport failure.' } }
export const outcomeUnknownError = (detail: string): string => `${FILTER_SORT_OUTCOME_UNKNOWN_ERROR} ${detail}`
export const refreshFailureError = (error: unknown): string => `Filter and sort was acknowledged, but refresh failed: ${errorMessage(error)}`
function nextSafeMonotonicIdentity(sequence: number): number | null { if (!Number.isSafeInteger(sequence)) return null; if (sequence >= 0) return sequence < Number.MAX_SAFE_INTEGER ? sequence + 1 : -1; return sequence > Number.MIN_SAFE_INTEGER ? sequence - 1 : null }
export const nextFilterSortSessionId = nextSafeMonotonicIdentity
export const nextFilterSortRequestId = nextSafeMonotonicIdentity
export const nextFilterSortOperationId = nextSafeMonotonicIdentity
export function normalizeRules(rules: readonly ColumnFilterRule[]): readonly ColumnFilterRule[] { return Object.freeze(rules.map((rule) => rule.kind !== 'list' ? Object.freeze({ ...rule }) : Object.freeze({ ...rule, values: Object.freeze(rule.values.slice(0, MAX_FILTER_LIST_VALUES)) }))) }
export const normalizeState = (state: FilterSortState): FilterSortState => Object.freeze({ rules: normalizeRules(state.rules) })
export function stateStoreWith(current: FilterSortStateStore, sheetId: string, state: FilterSortState): FilterSortStateStore { const exists = Object.prototype.hasOwnProperty.call(current.stateBySheet, sheetId); const bySheet = { ...current.stateBySheet }; let order = current.insertionOrder; if (!exists) { const oldest = order[0]; if (order.length >= MAX_FILTER_SORT_SHEETS && oldest !== undefined) { delete bySheet[oldest]; order = Object.freeze([...order.slice(1), sheetId]) } else order = Object.freeze([...order, sheetId]) }; return Object.freeze({ stateBySheet: Object.freeze({ ...bySheet, [sheetId]: Object.freeze({ rules: normalizeRules(state.rules) }) }), insertionOrder: order }) }
export function stateStoreWithout(current: FilterSortStateStore, sheetId: string): FilterSortStateStore { if (!Object.prototype.hasOwnProperty.call(current.stateBySheet, sheetId)) return current; const bySheet = { ...current.stateBySheet }; delete bySheet[sheetId]; return Object.freeze({ stateBySheet: Object.freeze(bySheet), insertionOrder: Object.freeze(current.insertionOrder.filter((id) => id !== sheetId)) }) }
export const openFilterDropdownState = (sheetId: string, colIndex: number) => Object.freeze({ status: 'open' as const, sheetId, colIndex })
export const snapshotFilterSortDraft = (draft: FilterSortDraftState): FilterSortDraftState => Object.freeze({ ...draft, selectedValues: Object.freeze([...draft.selectedValues]), availableValues: Object.freeze([...draft.availableValues]) })
export const closedFilterSortDraft = (sessionId: number): FilterSortDraftState => snapshotFilterSortDraft({ ...INITIAL_FILTER_SORT_DRAFT, sessionId })
export function sortFilterValues(values: readonly string[]): string[] { return [...new Set(values)].sort((left, right) => left === '' ? -1 : right === '' ? 1 : left.localeCompare(right, undefined, { numeric: true, sensitivity: 'base' })) }
export const sameValues = (left: readonly string[], right: readonly string[]): boolean => left.length === right.length && left.every((value) => new Set(right).has(value))
export function draftFromState(sessionId: number, sheetId: string, colIndex: number, state: FilterSortState, knownValues: readonly string[] = []): FilterSortDraftState { const rules = state.rules.filter((rule) => rule.colIndex === colIndex); const listRule = rules.find((rule): rule is Extract<ColumnFilterRule, { kind: 'list' }> => rule.kind === 'list'); const equalsRule = rules.find((rule): rule is Extract<ColumnFilterRule, { kind: 'equals' }> => rule.kind === 'equals'); const containsRule = rules.find((rule): rule is Extract<ColumnFilterRule, { kind: 'contains' }> => rule.kind === 'contains'); const rangeRule = rules.find((rule): rule is Extract<ColumnFilterRule, { kind: 'range' }> => rule.kind === 'range'); const availableValues = sortFilterValues([...(listRule?.values ?? []), ...knownValues]); return snapshotFilterSortDraft({ sessionId, sheetId, colIndex, searchInput: '', selectedValues: listRule ? sortFilterValues(listRule.values) : [...availableValues], selectionMode: listRule ? 'explicit' : 'all', conditionKind: equalsRule ? 'equals' : containsRule ? 'contains' : rangeRule ? 'range' : 'none', equalsInput: equalsRule?.value ?? '', containsInput: containsRule?.value ?? '', rangeMinInput: rangeRule?.min === undefined ? '' : String(rangeRule.min), rangeMaxInput: rangeRule?.max === undefined ? '' : String(rangeRule.max), availableValues }) }
function parseNumberInput(value: string): { valid: boolean; value?: number } { const trimmed = value.trim(); if (trimmed.length === 0) return { valid: true }; const parsed = Number(trimmed); return Number.isFinite(parsed) ? { valid: true, value: parsed } : { valid: false } }
export function deriveMutationState(current: FilterSortState, draft: FilterSortDraftState, intent: RunFilterSortMutationInput['intent']): { state: FilterSortState | null; error: string | null } { const colIndex = draft.colIndex; if (colIndex === null || !Number.isSafeInteger(colIndex) || colIndex < 0) return { state: null, error: FILTER_SORT_INVALID_INPUT_ERROR }; if (intent.kind === 'clear-filter' || intent.kind === 'clear-column') return { state: { rules: current.rules.filter((rule) => rule.colIndex !== colIndex) }, error: null }; const rules: ColumnFilterRule[] = current.rules.filter((rule) => rule.colIndex !== colIndex); const selected = sortFilterValues(draft.selectedValues.filter((value) => draft.availableValues.includes(value))); if (draft.availableValues.length > 0 && !sameValues(selected, draft.availableValues)) rules.push({ kind: 'list', colIndex, values: selected }); if (draft.conditionKind === 'equals' && draft.equalsInput.length > 0) rules.push({ kind: 'equals', colIndex, value: draft.equalsInput }); else if (draft.conditionKind === 'contains' && draft.containsInput.length > 0) rules.push({ kind: 'contains', colIndex, value: draft.containsInput }); else if (draft.conditionKind === 'range') { const min = parseNumberInput(draft.rangeMinInput); const max = parseNumberInput(draft.rangeMaxInput); if (!min.valid || !max.valid || (min.value !== undefined && max.value !== undefined && min.value > max.value)) return { state: null, error: FILTER_SORT_INVALID_INPUT_ERROR }; if (min.value !== undefined || max.value !== undefined) rules.push({ kind: 'range', colIndex, ...(min.value === undefined ? {} : { min: min.value }), ...(max.value === undefined ? {} : { max: max.value }) }) }; return { state: { rules }, error: null } }
export const lifecycleFor = (status: FilterSortLifecycleState['status'], sessionId: number, sheetId: string | null, colIndex: number | null, requestId: ProjectionRequestId | null = null): FilterSortLifecycleState => Object.freeze({ status, sessionId, requestId, sheetId, colIndex })
export function entrypointStateFor(status: FilterSortEntrypointState['status'], input: { readonly operationId?: number | null; readonly requestId?: ProjectionRequestId | null; readonly entrypoint?: FilterSortEntrypoint | null; readonly target?: FilterSortEntrypointTarget | null; readonly direction?: SortDirection | null; readonly attempt?: number; readonly error?: string } = {}): FilterSortEntrypointState { return Object.freeze({ status, operationId: input.operationId ?? null, requestId: input.requestId ?? null, entrypoint: input.entrypoint ?? null, target: input.target ?? null, direction: input.direction ?? null, attempt: input.attempt ?? 0, error: input.error ?? '' }) }
export const entrypointStateForTicket = (status: FilterSortEntrypointState['status'], ticket: import('./internal-types').FilterSortEntrypointTicket, error = ''): FilterSortEntrypointState => entrypointStateFor(status, { operationId: ticket.operationId, requestId: ticket.requestId, entrypoint: ticket.entrypoint, target: ticket.target, direction: ticket.direction, attempt: ticket.attempt, error })
export function nextEntrypointAttempt(previous: FilterSortEntrypointState, entrypoint: FilterSortEntrypoint, target: FilterSortEntrypointTarget, direction: SortDirection | null): number { return (previous.status === 'error' || previous.status === 'blocked' || previous.status === 'stale') && previous.entrypoint === entrypoint && previous.direction === direction && previous.target?.sheetId === target.sheetId && previous.target?.colIndex === target.colIndex ? previous.attempt < Number.MAX_SAFE_INTEGER ? previous.attempt + 1 : previous.attempt : 1 }
