import type { DemoMeta } from './registry-types'

export const DEMO_REGISTRY: DemoMeta[] = [
  {
    id: 'basics',
    titleKey: 'site.demoMeta.basics.title',
    blurbKey: 'site.demoMeta.basics.blurb',
    tags: ['editing', 'selection', 'keyboard'],
    backend: 'static',
    load: () => import('./pages/BasicsDemo'),
  },
  {
    id: 'formulas',
    titleKey: 'site.demoMeta.formulas.title',
    blurbKey: 'site.demoMeta.formulas.blurb',
    tags: ['formulas', 'worker', 'wasm'],
    backend: 'worker-wasm',
    load: () => import('./pages/FormulasDemo'),
  },
  {
    id: 'dynamic-arrays',
    titleKey: 'site.demoMeta.dynamic-arrays.title',
    blurbKey: 'site.demoMeta.dynamic-arrays.blurb',
    tags: ['formulas', 'arrays', 'worker'],
    backend: 'worker-ts',
    load: () => import('./pages/DynamicArraysDemo'),
  },
  {
    id: 'custom-formulas',
    titleKey: 'site.demoMeta.custom-formulas.title',
    blurbKey: 'site.demoMeta.custom-formulas.blurb',
    tags: ['formulas', 'custom', 'async'],
    backend: 'worker-wasm',
    load: () => import('./pages/CustomFormulasDemo'),
  },
  {
    id: 'find-replace',
    titleKey: 'site.demoMeta.find-replace.title',
    blurbKey: 'site.demoMeta.find-replace.blurb',
    tags: ['search', 'editing'],
    backend: 'static',
    load: () => import('./pages/FindReplaceDemo'),
  },
  {
    id: 'conditional-formatting',
    titleKey: 'site.demoMeta.conditional-formatting.title',
    blurbKey: 'site.demoMeta.conditional-formatting.blurb',
    tags: ['formatting', 'rules'],
    backend: 'static',
    load: () => import('./pages/ConditionalFormattingDemo'),
  },
  {
    id: 'data-validation',
    titleKey: 'site.demoMeta.data-validation.title',
    blurbKey: 'site.demoMeta.data-validation.blurb',
    tags: ['validation', 'rules', 'editing'],
    backend: 'static',
    load: () => import('./pages/DataValidationDemo'),
  },
  {
    id: 'named-ranges',
    titleKey: 'site.demoMeta.named-ranges.title',
    blurbKey: 'site.demoMeta.named-ranges.blurb',
    tags: ['names', 'navigation'],
    backend: 'static',
    load: () => import('./pages/NamedRangesDemo'),
  },
  {
    id: 'history',
    titleKey: 'site.demoMeta.history.title',
    blurbKey: 'site.demoMeta.history.blurb',
    tags: ['undo', 'editing'],
    backend: 'static',
    load: () => import('./pages/HistoryDemo'),
  },
  {
    id: 'data-tools',
    titleKey: 'site.demoMeta.data-tools.title',
    blurbKey: 'site.demoMeta.data-tools.blurb',
    tags: ['clipboard', 'data'],
    backend: 'static',
    load: () => import('./pages/DataToolsDemo'),
  },
  {
    id: 'filter-sort',
    titleKey: 'site.demoMeta.filter-sort.title',
    blurbKey: 'site.demoMeta.filter-sort.blurb',
    tags: ['filter', 'sort', 'data'],
    backend: 'static',
    load: () => import('./pages/FilterSortDemo'),
  },
  {
    id: 'collaboration',
    titleKey: 'site.demoMeta.collaboration.title',
    blurbKey: 'site.demoMeta.collaboration.blurb',
    tags: ['comments', 'collab'],
    backend: 'static',
    load: () => import('./pages/CollaborationDemo'),
  },
  {
    id: 'protection-print',
    titleKey: 'site.demoMeta.protection-print.title',
    blurbKey: 'site.demoMeta.protection-print.blurb',
    tags: ['protection', 'print'],
    backend: 'static',
    load: () => import('./pages/ProtectionPrintDemo'),
  },
  {
    id: 'performance',
    titleKey: 'site.demoMeta.performance.title',
    blurbKey: 'site.demoMeta.performance.blurb',
    tags: ['performance', 'worker', 'wasm'],
    backend: 'worker-wasm',
    load: () => import('./pages/PerformanceDemo'),
  },
]

export function findDemo(id: string): DemoMeta | undefined {
  return DEMO_REGISTRY.find((demo) => demo.id === id)
}
